import { Resend } from "resend";
import type { WeeklyReportSections } from "@/lib/intelligence/types";

type SendEmailInput = {
  weekLabel: string;
  weekStart: string;
  weekEnd: string;
  sections: WeeklyReportSections;
};

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function section(title: string, body: string): string {
  return `
    <tr>
      <td style="padding:0 0 28px;">
        <p style="margin:0 0 10px;font-size:11px;letter-spacing:0.14em;text-transform:uppercase;color:#8a8176;">${escapeHtml(title)}</p>
        <p style="margin:0;font-size:15px;line-height:1.75;color:#3d3832;font-family:Georgia,'Times New Roman',serif;">${escapeHtml(body)}</p>
      </td>
    </tr>`;
}

function listSection(title: string, items: string[]): string {
  if (!items.length) return "";
  const lis = items
    .map(
      (item) =>
        `<li style="margin:0 0 8px;font-size:14px;line-height:1.65;color:#4a443e;">${escapeHtml(item)}</li>`,
    )
    .join("");
  return `
    <tr>
      <td style="padding:0 0 28px;">
        <p style="margin:0 0 10px;font-size:11px;letter-spacing:0.14em;text-transform:uppercase;color:#8a8176;">${escapeHtml(title)}</p>
        <ul style="margin:0;padding:0 0 0 18px;">${lis}</ul>
      </td>
    </tr>`;
}

export async function sendWeeklyIntelligenceEmail(
  input: SendEmailInput,
): Promise<void> {
  const apiKey = process.env.RESEND_API_KEY?.trim();
  const from = process.env.INTELLIGENCE_EMAIL_FROM?.trim();
  const to = process.env.INTELLIGENCE_EMAIL_TO?.trim();

  if (!apiKey || !from || !to) {
    throw new Error("RESEND_API_KEY, INTELLIGENCE_EMAIL_FROM, INTELLIGENCE_EMAIL_TO required");
  }

  const resend = new Resend(apiKey);
  const subject = `Hourglass Weekly Intelligence Brief — Week of ${input.weekLabel}`;
  const { sections } = input;

  const html = `
<!DOCTYPE html>
<html>
  <body style="margin:0;padding:32px 20px;background:#efe8de;">
    <table width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;margin:0 auto;background:#f7f3ee;border:1px solid #e4dbcf;">
      <tr>
        <td style="padding:36px 32px 8px;">
          <p style="margin:0 0 6px;font-size:10px;letter-spacing:0.2em;text-transform:uppercase;color:#8a8176;">Hourglass Diamonds · Internal</p>
          <h1 style="margin:0;font-size:22px;font-weight:400;color:#1a1816;font-family:Georgia,'Times New Roman',serif;">Weekly Intelligence Brief</h1>
          <p style="margin:10px 0 0;font-size:12px;color:#6a635c;">${escapeHtml(input.weekStart)} — ${escapeHtml(input.weekEnd)}</p>
        </td>
      </tr>
      ${section("Executive Summary", sections.executive_summary)}
      ${section("Traffic Health", sections.traffic_summary)}
      ${section("Diamond Studio Intelligence", sections.diamond_studio_summary)}
      ${section("Landing Page Winners", sections.landing_page_summary)}
      ${listSection("Opportunities", sections.opportunities)}
      ${listSection("Problems", sections.problems)}
      ${listSection("Recommended Actions", sections.recommendations)}
      <tr>
        <td style="padding:8px 32px 36px;font-size:11px;color:#9a9084;">Generated by the Hourglass Intelligence Engine. Not for external distribution.</td>
      </tr>
    </table>
  </body>
</html>`;

  const { error } = await resend.emails.send({
    from,
    to: [to],
    subject,
    html,
  });

  if (error) {
    throw new Error(error.message);
  }
}
