import assert from "node:assert/strict";
import { describe, it } from "node:test";
import type { ProjectJob } from "@/lib/continuum/client-memory/project-jobs/types";
import type { ProjectJobWriter } from "@/lib/continuum/client-memory/project-jobs/writer";
import type { SourceCommunicationEvent } from "@/lib/continuum/source-events/types";
import { collectCanonicalActionables } from "@/lib/continuum/chief-of-staff/operating-loop/collect";
import { fingerprintCanonicalState } from "./fingerprint";
import { parseSterlingIntent, runSterling } from "./engine";
import { matchHoldCondition } from "./holds/match";
import { parseConditionalHold } from "./holds/parser";
import { InMemoryConditionalHoldRepository } from "./holds/repository";
import { ConditionalHoldService } from "./holds/service";
import { partitionConditionalHoldCapture } from "./holds/capture";
import type { ConditionalHoldCondition, CreateConditionalHoldInput } from "./holds/types";
import type { SterlingTruth } from "./types";

const NOW = new Date("2026-10-03T14:00:00.000Z");
const JOB: ProjectJob = { jobId: "job-ben", projectId: "project-ben", kind: "required_action", subject: "Send Ben the revised estimate", detail: null, waitingOnActor: "founder", associatedPersonId: "person-ben", state: "open", dueAt: null, deferredUntil: null, resolvedAt: null, cancelledAt: null, createdAt: "2026-10-01T12:00:00.000Z", updatedAt: "2026-10-03T13:00:00.000Z", createdBy: "founder", sourceSystem: "gmail", sourceRef: "gmail-thread:thread-ben", createdMutationId: "mutation-1" };
const TRUTH: SterlingTruth = { generatedAt: NOW.toISOString(), sourceWatermark: "wm", sourceStatus: "current", openJobs: [JOB], candidates: [], anomalies: [], today: [{ id: JOB.jobId, title: JOB.subject, why: "Founder action", projectId: JOB.projectId, projectTitle: "Ben ring", personName: "Ben", owner: "founder", state: "Up next", proposedNextAction: JOB.subject, dueAt: null, sourceRefs: [JOB.sourceRef!], authoritative: true, clientFacing: true, productionBlocker: false }] };
const scope = { projectId: JOB.projectId, personLabel: "Ben", threadId: "thread-ben", cadId: null };

describe("Sterling conditional holds", () => {
  it("recognizes hold intent", () => assert.equal(parseSterlingIntent("Hold Ben until Monday"), "conditional-hold"));
  it("recognizes snooze and natural hold phrasings", () => {
    assert.equal(parseSterlingIntent("Snooze Ben until tomorrow afternoon"), "conditional-hold");
    assert.equal(parseSterlingIntent("Leave Ben alone until I hear back"), "conditional-hold");
    assert.equal(parseSterlingIntent("Don't bug me about Ben unless something changes"), "conditional-hold");
  });
  it("does not pretend SMS is observable", () => { const row = parseConditionalHold("Hold off until I text Ben again", TRUTH, NOW); assert.equal(row.kind, "clarification"); assert.match(row.kind === "clarification" ? row.message : "", /cannot observe.*SMS|cannot observe.*text/i); });
  it("offers a manual or email alternative for SMS", () => { const row = parseConditionalHold("Hold off until I text Ben again", TRUTH, NOW); assert.match(row.kind === "clarification" ? row.message : "", /manually confirm.*email/i); });
  it("proposes a founder-email hold", () => assert.equal(proposal("Hold Ben until I email Ben again").condition.kind, "until_founder_contact"));
  it("proposes an external-reply hold", () => assert.equal(proposal("Hold Ben until Ben replies").condition.kind, "until_external_reply"));
  it("proposes a CAD delivery hold", () => assert.equal(proposal("Hold Ben until the CAD arrives").condition.kind, "until_source_event"));
  it("rejects unobservable payment clearing", () => assert.equal(parseConditionalHold("Hold Ben until payment clears", TRUTH, NOW).kind, "clarification"));
  it("resolves tomorrow afternoon in New York", () => { const row = proposal("Hold Ben until tomorrow afternoon"); assert.equal(row.condition.kind, "until_time"); if (row.condition.kind === "until_time") assert.equal(row.condition.resumeAt, "2026-10-04T19:00:00.000Z"); });
  it("treats snooze as an explicit time-bounded hold", () => { const row = proposal("Snooze Ben until tomorrow afternoon"); assert.equal(row.condition.kind, "until_time"); });
  it("resolves next Monday morning", () => { const row = proposal("Hold Ben until Monday morning"); assert.equal(row.condition.kind, "until_time"); if (row.condition.kind === "until_time") assert.equal(row.condition.resumeAt, "2026-10-05T13:00:00.000Z"); });
  it("asks when this is ambiguous", () => assert.equal(parseConditionalHold("Hold this until Monday", { ...TRUTH, openJobs: [JOB, { ...JOB, jobId: "other", subject: "Call Alex" }] }, NOW).kind, "clarification"));
  it("builds a founder-review proposal without mutation", () => { const result = runSterling({ truth: TRUTH, intent: "conditional-hold", query: "Hold Ben until Ben replies", now: NOW }); assert.equal(result.proposals[0]?.kind, "conditional_hold"); assert.equal(result.proposals[0]?.status, "review-required"); });
  it("suppresses held jobs from Today collection", () => assert.equal(collectCanonicalActionables({ jobs: [JOB], projects: new Map(), nowIso: NOW.toISOString(), heldJobIds: new Set([JOB.jobId]) }).length, 0));
  it("does not suppress an unheld job", () => assert.equal(collectCanonicalActionables({ jobs: [JOB], projects: new Map(), nowIso: NOW.toISOString(), heldJobIds: new Set() }).length, 1));
  it("ignores source events from before activation", () => assert.equal(matchHoldCondition({ condition: external(), activatedAt: NOW.toISOString(), events: [event({ timestamp: "2026-10-03T13:59:59.000Z" })], now: NOW }), null));
  it("matches a newer scoped client reply", () => assert.equal(matchHoldCondition({ condition: external(), activatedAt: NOW.toISOString(), events: [event()], now: new Date("2026-10-03T15:01:00Z") })?.sourceRef, "gmail:message-1"));
  it("rejects a reply for the wrong project", () => assert.equal(matchHoldCondition({ condition: external(), activatedAt: NOW.toISOString(), events: [event({ projectId: "wrong" })], now: NOW }), null));
  it("rejects a reply for the wrong thread", () => assert.equal(matchHoldCondition({ condition: external(), activatedAt: NOW.toISOString(), events: [event({ threadId: "wrong" })], now: NOW }), null));
  it("rejects nonblocking chatter", () => assert.equal(matchHoldCondition({ condition: external(), activatedAt: NOW.toISOString(), events: [event({ semanticClass: "client_replies_nonblocking" })], now: NOW }), null));
  it("rejects automated/system mail", () => assert.equal(matchHoldCondition({ condition: external(), activatedAt: NOW.toISOString(), events: [event({ actor: "system" })], now: NOW }), null));
  it("requires outbound founder evidence for contact", () => { const condition: ConditionalHoldCondition = { kind: "until_founder_contact", scope, observableSources: ["gmail"] }; assert.equal(matchHoldCondition({ condition, activatedAt: NOW.toISOString(), events: [event({ direction: "inbound", actor: "client" })], now: NOW }), null); assert.ok(matchHoldCondition({ condition, activatedAt: NOW.toISOString(), events: [event({ direction: "outbound", actor: "founder", semanticClass: "founder_updates_client" })], now: NOW })); });
  it("requires an exact CAD identifier when supplied", () => { const condition: ConditionalHoldCondition = { kind: "until_source_event", scope: { ...scope, cadId: "CAD-7" }, semanticClass: "vendor_delivers_artifact", observableSources: ["gmail"] }; assert.equal(matchHoldCondition({ condition, activatedAt: NOW.toISOString(), events: [event({ actor: "vendor_shop", semanticClass: "vendor_delivers_artifact", cadIds: ["CAD-8"] })], now: NOW }), null); assert.ok(matchHoldCondition({ condition, activatedAt: NOW.toISOString(), events: [event({ actor: "vendor_shop", semanticClass: "vendor_delivers_artifact", cadIds: ["CAD-7"] })], now: NOW })); });
  it("marks time reached but not before", () => { const condition: ConditionalHoldCondition = { kind: "until_time", resumeAt: "2026-10-04T13:00:00Z", timezone: "America/New_York" }; assert.equal(matchHoldCondition({ condition, activatedAt: NOW.toISOString(), events: [], now: NOW }), null); assert.ok(matchHoldCondition({ condition, activatedAt: NOW.toISOString(), events: [], now: new Date("2026-10-04T13:00:00Z") })); });
  it("keeps unsupported business events closed", () => assert.equal(matchHoldCondition({ condition: { kind: "until_business_event", event: "payment-cleared", observable: false }, activatedAt: NOW.toISOString(), events: [event()], now: NOW }), null));
  it("creates holds idempotently by proposal", async () => { const repository = new InMemoryConditionalHoldRepository(); const input = createInput(); assert.equal((await repository.create(input)).idempotent, false); assert.equal((await repository.create(input)).idempotent, true); });
  it("condition-met remains suppressed until founder resume", async () => { const repository = new InMemoryConditionalHoldRepository(); const input = createInput(); await repository.create(input); await repository.markConditionMet(input.holdId, "2026-10-03T15:00:00Z", { sourceRef: "gmail:1", observedAt: "2026-10-03T15:00:00Z", summary: "reply" }); assert.equal((await repository.listActive())[0]?.status, "condition_met"); await repository.resume(input.holdId, "2026-10-03T15:01:00Z", { sourceRef: "founder-confirmation", observedAt: "2026-10-03T15:01:00Z", summary: "confirmed" }); assert.equal((await repository.listActive()).length, 0); });
  it("double resume is idempotent", async () => { const repository = new InMemoryConditionalHoldRepository(); const input = createInput(); await repository.create(input); const evidence = { sourceRef: "gmail:1", observedAt: "2026-10-03T15:00:00Z", summary: "reply" }; await repository.markConditionMet(input.holdId, evidence.observedAt, evidence); await repository.resume(input.holdId, evidence.observedAt, evidence); assert.equal((await repository.resume(input.holdId, evidence.observedAt, evidence)).idempotent, true); });
  it("blocks stale activation before hiding work", async () => { const repository = new InMemoryConditionalHoldRepository(); const service = new ConditionalHoldService({ repository, jobs: writer({ ...JOB, updatedAt: "newer" }) }); const result = await service.activate(createInput()); assert.deepEqual(result, { ok: false, reason: "stale-job" }); assert.equal((await repository.listActive()).length, 0); });
  it("evaluates evidence but waits for founder confirmation", async () => { const repository = new InMemoryConditionalHoldRepository(); const service = new ConditionalHoldService({ repository, jobs: writer(JOB) }); await service.activate(createInput()); await service.evaluate([event()], new Date("2026-10-03T15:01:00Z")); assert.equal((await repository.listActive())[0]?.status, "condition_met"); await service.confirmResume(createInput().holdId, new Date("2026-10-03T15:02:00Z")); assert.equal((await repository.listActive()).length, 0); });
  it("closes a hold when its canonical job completes", async () => { const repository = new InMemoryConditionalHoldRepository(); const mutable = { current: JOB }; const jobs = writer(JOB, mutable); const service = new ConditionalHoldService({ repository, jobs }); await service.activate(createInput()); mutable.current = { ...JOB, state: "resolved", resolvedAt: "2026-10-03T15:00:00Z" }; await service.evaluate([], new Date("2026-10-03T15:01:00Z")); assert.equal((await repository.get(createInput().holdId))?.status, "closed_terminal"); });
  it("splits a Speak hold from separate active work", () => { const split = partitionConditionalHoldCapture("Ben CAD is fine for now, hold it until I text him again. Nate resin needs done today."); assert.deepEqual(split.holds, ["Ben CAD is fine for now, hold it until I text him again."]); assert.equal(split.ordinary, "Nate resin needs done today."); });
});

function proposal(text: string) { const row = parseConditionalHold(text, TRUTH, NOW); assert.equal(row.kind, "proposal"); return row as Extract<typeof row, { kind: "proposal" }>; }
function external(): ConditionalHoldCondition { return { kind: "until_external_reply", scope, observableSources: ["gmail"] }; }
function createInput(): CreateConditionalHoldInput { return { holdId: "00000000-0000-5000-8000-000000000001", entityType: "job", entityId: JOB.jobId, projectId: JOB.projectId, createdAt: NOW.toISOString(), createdBy: "founder", reason: "wait", condition: external(), sourceRefs: [JOB.sourceRef!], approvalProposalId: "00000000-0000-5000-8000-000000000002", provenance: "sterling-founder-approved", activatedAt: NOW.toISOString(), expectedEntityUpdatedAt: JOB.updatedAt, currentStateFingerprint: fingerprintCanonicalState(JOB) }; }
function event(overrides: Partial<SourceCommunicationEvent> = {}): SourceCommunicationEvent { return { sourceType: "gmail", sourceRef: "gmail:message-1", messageId: "message-1", threadId: "thread-ben", timestamp: "2026-10-03T15:00:00.000Z", direction: "inbound", actor: "client", subject: "Re: estimate", authorOwnedText: "Please proceed", quotedText: "", attachmentFilenames: [], hasAttachments: false, cadIds: [], orderIds: [], productionJobIds: [], personLabel: "Ben", projectId: JOB.projectId, workLoopId: null, semanticClass: "client_approves", evidenceExcerpt: "Please proceed", workIdentityBasis: "project", provenance: "indexed_gmail", ...overrides }; }
function writer(initial: ProjectJob, mutable = { current: initial }): ProjectJobWriter { return { getJob: async (projectId, jobId) => mutable.current.projectId === projectId && mutable.current.jobId === jobId ? mutable.current : null, createJob: async () => { throw new Error("not used"); }, mutateJob: async () => { throw new Error("not used"); } }; }
