/**
 * Fixed fixtures for deterministic fan-out coverage tests.
 */

import type { FanOutContentRecord, FanOutQuestion } from "./types";

export const FIXTURE_FAN_OUT_QUESTIONS: FanOutQuestion[] = [
  {
    id: "fan-out-q:fixture-sparkle",
    canonicalQuestion: "What makes one diamond sparkle more than another?",
    queryFamily: "cut-and-sparkle",
    searchIntent: "informational",
    audienceStage: "researching",
    geography: "unspecified",
    commercialValue: 8,
    authorityValue: 10,
    source: "seed-curated",
    status: "active",
    matchTerms: ["sparkle", "light performance", "cut"],
    entities: ["sparkle", "cut"],
    topics: ["cut", "light-performance"],
    duplicateOfId: null,
    createdAt: "2026-07-27T00:00:00.000Z",
    updatedAt: "2026-07-27T00:00:00.000Z",
  },
  {
    id: "fan-out-q:fixture-waxhaw",
    canonicalQuestion: "Where should I buy an engagement ring near Waxhaw?",
    queryFamily: "local-charlotte-intent",
    searchIntent: "local",
    audienceStage: "ready-to-contact",
    geography: "waxhaw",
    commercialValue: 10,
    authorityValue: 8,
    source: "seed-curated",
    status: "active",
    matchTerms: ["waxhaw", "engagement ring", "near waxhaw"],
    entities: ["waxhaw"],
    topics: ["local"],
    duplicateOfId: null,
    createdAt: "2026-07-27T00:00:00.000Z",
    updatedAt: "2026-07-27T00:00:00.000Z",
  },
  {
    id: "fan-out-q:fixture-care",
    canonicalQuestion: "How should I care for an engagement ring day to day?",
    queryFamily: "maintenance-repairs-ownership",
    searchIntent: "informational",
    audienceStage: "post-purchase",
    geography: "unspecified",
    commercialValue: 4,
    authorityValue: 6,
    source: "seed-curated",
    status: "active",
    matchTerms: ["care for", "maintenance", "clean", "repair"],
    entities: ["ring-care"],
    topics: ["maintenance"],
    duplicateOfId: null,
    createdAt: "2026-07-27T00:00:00.000Z",
    updatedAt: "2026-07-27T00:00:00.000Z",
  },
  {
    id: "fan-out-q:fixture-trust-dupe",
    canonicalQuestion: "How can I tell whether a jeweler is trustworthy?",
    queryFamily: "buying-process-anxiety",
    searchIntent: "commercial",
    audienceStage: "comparing",
    geography: "unspecified",
    commercialValue: 9,
    authorityValue: 10,
    source: "seed-curated",
    status: "active",
    matchTerms: ["trustworthy", "trust", "jeweler"],
    entities: ["trust"],
    topics: ["trust"],
    duplicateOfId: null,
    createdAt: "2026-07-27T00:00:00.000Z",
    updatedAt: "2026-07-27T00:00:00.000Z",
  },
  {
    id: "fan-out-q:fixture-trust-dupe-copy",
    canonicalQuestion: "How can I tell whether a jeweler is trustworthy?",
    queryFamily: "trust-ethics-credibility",
    searchIntent: "informational",
    audienceStage: "comparing",
    geography: "unspecified",
    commercialValue: 8,
    authorityValue: 10,
    source: "seed-curated",
    status: "duplicate",
    matchTerms: ["trustworthy", "trust"],
    entities: ["trust"],
    topics: ["trust"],
    duplicateOfId: "fan-out-q:fixture-trust-dupe",
    createdAt: "2026-07-27T00:00:00.000Z",
    updatedAt: "2026-07-27T00:00:00.000Z",
  },
  {
    id: "fan-out-q:fixture-online-risky",
    canonicalQuestion: "Is buying a diamond online risky?",
    queryFamily: "pricing-and-budgeting",
    searchIntent: "commercial",
    audienceStage: "comparing",
    geography: "unspecified",
    commercialValue: 8,
    authorityValue: 8,
    source: "seed-curated",
    status: "active",
    matchTerms: ["buying online", "online risky"],
    entities: ["online-purchase"],
    topics: ["trust", "buying-process"],
    duplicateOfId: null,
    createdAt: "2026-07-27T00:00:00.000Z",
    updatedAt: "2026-07-27T00:00:00.000Z",
  },
  {
    id: "fan-out-q:fixture-big-box",
    canonicalQuestion: "Should I buy from a big box jewelry retailer?",
    queryFamily: "jeweler-comparison",
    searchIntent: "commercial",
    audienceStage: "comparing",
    geography: "unspecified",
    commercialValue: 7,
    authorityValue: 7,
    source: "seed-curated",
    status: "active",
    matchTerms: ["big box", "retailer", "chain"],
    entities: ["retail-store"],
    topics: ["jeweler-comparison"],
    duplicateOfId: null,
    createdAt: "2026-07-27T00:00:00.000Z",
    updatedAt: "2026-07-27T00:00:00.000Z",
  },
];

export const FIXTURE_FAN_OUT_INVENTORY: FanOutContentRecord[] = [
  {
    id: "fan-out-content:fixture-sparkle-guide",
    url: "/diamond-guide/diamond-sparkle-explained",
    title: "Diamond Sparkle Explained",
    contentType: "diamond-guide-article",
    summary:
      "What makes one diamond sparkle more than another: cut quality, light return, brilliance, and scintillation.",
    topics: ["cut", "light-performance", "sparkle"],
    entities: ["sparkle", "cut"],
    geography: "unspecified",
    publicationStatus: "published",
    publishedOrUpdatedAt: null,
    hasStructuredData: false,
    sourceSystemId: "fixture:sparkle-guide",
    canonicalSourceId: "/diamond-guide/diamond-sparkle-explained",
    searchableText:
      "Diamond Sparkle Explained What makes one diamond sparkle more than another cut light-performance sparkle",
    relatedHrefs: ["/diamond-guide/how-diamond-cut-affects-sparkle", "/diamond-intelligence"],
  },
  {
    id: "fan-out-content:fixture-cut-faq",
    url: "/diamond-guide/what-is-diamond-cut#faq-does-cut-affect-sparkle",
    title: "Does cut affect sparkle?",
    contentType: "faq",
    summary:
      "Yes. Cut quality governs how light returns through the diamond and drives sparkle more than carat alone.",
    topics: ["cut", "cut-and-sparkle"],
    entities: ["cut"],
    geography: "unspecified",
    publicationStatus: "published",
    publishedOrUpdatedAt: null,
    hasStructuredData: true,
    sourceSystemId: "fixture:cut-faq",
    canonicalSourceId: "/diamond-guide/what-is-diamond-cut",
    searchableText:
      "Does cut affect sparkle Yes cut quality light sparkle cut cut-and-sparkle",
    relatedHrefs: [],
  },
  {
    id: "fan-out-content:fixture-cut-faq-sibling",
    url: "/diamond-guide/what-is-diamond-cut#faq-is-cut-the-most-important",
    title: "Is cut the most important of the Four Cs?",
    contentType: "faq",
    summary: "Cut often matters most for sparkle; color and clarity still matter.",
    topics: ["cut", "cut-and-sparkle"],
    entities: ["cut"],
    geography: "unspecified",
    publicationStatus: "published",
    publishedOrUpdatedAt: null,
    hasStructuredData: true,
    sourceSystemId: "fixture:cut-faq-sibling",
    canonicalSourceId: "/diamond-guide/what-is-diamond-cut",
    searchableText: "Is cut the most important Four Cs sparkle",
    relatedHrefs: [],
  },
  {
    id: "fan-out-content:fixture-charlotte-faq",
    url: "/diamond-guide/charlotte-diamond-advisor-guide#faq-areas",
    title: "What areas around Charlotte does Hourglass serve?",
    contentType: "faq",
    summary:
      "Hourglass serves the Charlotte metro, including Waxhaw, Weddington, Marvin, and Union County communities.",
    topics: ["local", "trust"],
    entities: ["charlotte", "waxhaw"],
    geography: "charlotte-metro",
    publicationStatus: "published",
    publishedOrUpdatedAt: null,
    hasStructuredData: true,
    sourceSystemId: "fixture:charlotte-faq",
    canonicalSourceId: "/diamond-guide/charlotte-diamond-advisor-guide",
    searchableText:
      "What areas around Charlotte does Hourglass serve Waxhaw Charlotte metro local",
    relatedHrefs: [],
  },
  {
    id: "fan-out-content:fixture-charlotte-weak-faq",
    url: "/diamond-guide/charlotte-diamond-advisor-guide#faq-showroom",
    title: "Does Hourglass have a public showroom?",
    contentType: "faq",
    summary: "Hourglass works by private appointment, not a walk-in showroom floor.",
    topics: ["local", "trust"],
    entities: ["charlotte"],
    geography: "charlotte",
    publicationStatus: "published",
    publishedOrUpdatedAt: null,
    hasStructuredData: true,
    sourceSystemId: "fixture:charlotte-weak-faq",
    canonicalSourceId: "/diamond-guide/charlotte-diamond-advisor-guide",
    searchableText: "public showroom Charlotte appointment local trust",
    relatedHrefs: [],
  },
  {
    id: "fan-out-content:fixture-approach",
    url: "/our-approach#excellent-not-recommended",
    title: "Why do some diamonds receive excellent grades but still aren't recommended?",
    contentType: "approach-qa",
    summary:
      "Excellent grades are a starting point. We reject diamonds that lack optical performance despite paper grades.",
    topics: ["trust", "approach", "quality"],
    entities: ["selection-philosophy", "graduate-gemologist"],
    geography: "unspecified",
    publicationStatus: "published",
    publishedOrUpdatedAt: null,
    hasStructuredData: false,
    sourceSystemId: "fixture:approach",
    canonicalSourceId: "/our-approach",
    searchableText:
      "excellent grades recommended reject selection philosophy graduate gemologist trust",
    relatedHrefs: [],
  },
  {
    id: "fan-out-content:fixture-engagement-generic",
    url: "/engagement-rings",
    title: "Engagement Rings",
    contentType: "core-page",
    summary:
      "Private engagement ring design in Charlotte with custom process and Concierge conversation.",
    topics: ["engagement-ring", "custom-design", "local"],
    entities: ["engagement-ring", "charlotte"],
    geography: "charlotte",
    publicationStatus: "published",
    publishedOrUpdatedAt: null,
    hasStructuredData: true,
    sourceSystemId: "fixture:engagement",
    canonicalSourceId: "/engagement-rings",
    searchableText:
      "Engagement Rings Private engagement ring design Charlotte custom Concierge",
    relatedHrefs: ["/concierge"],
  },
];
