/**
 * V1.1 fan-out question universe expansion.
 *
 * Adds ~121 new active canonical questions on top of the ~44 curated in
 * seed-questions.ts, taking the overall active universe to roughly 165
 * questions across all 14 query families. Every draft here is additive:
 * none of these duplicate the existing V1 actives (e.g. the Four Cs,
 * sparkle, natural-vs-lab, or Charlotte "best jeweler" questions already
 * seeded). Where a new question is a near-phrasing of another canonical,
 * it is marked status: "duplicate" with duplicateOf pointing at the
 * canonical text instead of being added as a second active question.
 *
 * Also includes a small number of status: "deferred" (considered but not
 * yet in scope) and status: "rejected" (navigational brand noise) entries
 * so downstream triage/audit tooling has realistic non-active examples to
 * exercise against.
 */

import { SEED_STAMP_V11, type SeedDraft } from "./seed-builder";

export const V11_EXPANSION_DRAFTS: SeedDraft[] = [
  // ---------------------------------------------------------------------
  // beginner-education (+9)
  // ---------------------------------------------------------------------
  {
    question: "What are the different parts of an engagement ring called?",
    family: "beginner-education",
    intent: "informational",
    stage: "discovering",
    commercial: 4,
    authority: 6,
    matchTerms: ["parts of a ring", "setting", "shank", "head", "prongs", "ring anatomy"],
    entities: ["ring-anatomy"],
    topics: ["education", "buying-guides"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What does a diamond certificate actually tell you?",
    family: "beginner-education",
    intent: "informational",
    stage: "researching",
    commercial: 6,
    authority: 9,
    matchTerms: ["diamond certificate", "grading report", "what it tells you", "gia report"],
    entities: ["grading-report"],
    topics: ["education", "certification"],
    source: "expert-curated",
    aliases: ["Which diamond certificate should I trust?"],
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What doesn't a diamond certificate tell you?",
    family: "beginner-education",
    intent: "informational",
    stage: "researching",
    commercial: 7,
    authority: 10,
    matchTerms: [
      "certificate doesn't show",
      "limitations",
      "paper grade",
      "light performance",
      "certificate blind spots",
    ],
    entities: ["grading-report", "light-performance"],
    topics: ["education", "certification", "cut"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What questions should I ask a jeweler before buying?",
    family: "beginner-education",
    intent: "informational",
    stage: "comparing",
    commercial: 8,
    authority: 8,
    matchTerms: ["questions to ask", "jeweler", "before buying", "checklist"],
    entities: ["buying-checklist"],
    topics: ["education", "buying-process"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "When should I start shopping for an engagement ring?",
    family: "beginner-education",
    intent: "informational",
    stage: "discovering",
    commercial: 6,
    authority: 5,
    matchTerms: ["when to start", "how early", "timeline", "shopping timeline"],
    entities: ["timeline"],
    topics: ["education", "buying-process"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What mistakes do first-time engagement ring buyers make?",
    family: "beginner-education",
    intent: "informational",
    stage: "discovering",
    commercial: 7,
    authority: 8,
    matchTerms: ["first-time buyer", "common mistakes", "avoid mistakes", "beginner mistakes"],
    entities: ["buyer-mistakes"],
    topics: ["education", "buying-process"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Do I need to understand all four Cs to buy well?",
    family: "beginner-education",
    intent: "informational",
    stage: "discovering",
    commercial: 6,
    authority: 7,
    matchTerms: ["four cs", "do i need to know", "basics", "how much to learn"],
    entities: ["four-cs"],
    topics: ["education"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Which diamond qualities matter most for everyday beauty?",
    family: "beginner-education",
    intent: "informational",
    stage: "researching",
    commercial: 7,
    authority: 8,
    matchTerms: ["everyday beauty", "qualities that matter", "which qualities", "wearability"],
    entities: ["diamond-quality"],
    topics: ["education", "quality"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How is an engagement ring different from a wedding band?",
    family: "beginner-education",
    intent: "informational",
    stage: "discovering",
    commercial: 4,
    authority: 5,
    matchTerms: ["engagement ring vs wedding band", "difference", "wedding band"],
    entities: ["wedding-band"],
    topics: ["education"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },

  // ---------------------------------------------------------------------
  // diamond-quality (+9)
  // ---------------------------------------------------------------------
  {
    question: "What clarity grade is the best value for the price?",
    family: "diamond-quality",
    intent: "commercial",
    stage: "comparing",
    commercial: 8,
    authority: 8,
    matchTerms: ["clarity grade", "best value", "price", "VS1 VS2", "value clarity"],
    entities: ["clarity"],
    topics: ["quality", "pricing"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How does diamond color grade affect how a diamond looks?",
    family: "diamond-quality",
    intent: "informational",
    stage: "researching",
    commercial: 6,
    authority: 8,
    matchTerms: ["color grade", "appearance", "yellow tint", "face-up color"],
    entities: ["color-grade"],
    topics: ["quality", "color"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Are inclusions in a diamond a problem?",
    family: "diamond-quality",
    intent: "informational",
    stage: "researching",
    commercial: 6,
    authority: 8,
    matchTerms: ["inclusions", "problem", "visible inclusions", "clarity characteristics"],
    entities: ["inclusions"],
    topics: ["quality", "clarity"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Why do polish and symmetry matter in a diamond?",
    family: "diamond-quality",
    intent: "informational",
    stage: "researching",
    commercial: 5,
    authority: 8,
    matchTerms: ["polish", "symmetry", "finish grade", "why it matters"],
    entities: ["polish-symmetry"],
    topics: ["quality", "cut"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Are diamonds durable enough for everyday wear?",
    family: "diamond-quality",
    intent: "informational",
    stage: "researching",
    commercial: 6,
    authority: 7,
    matchTerms: ["durability", "everyday wear", "hardness", "chip or crack"],
    entities: ["durability"],
    topics: ["quality", "maintenance"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What does eye-clean mean versus technically flawless?",
    family: "diamond-quality",
    intent: "informational",
    stage: "researching",
    commercial: 7,
    authority: 9,
    matchTerms: ["eye-clean", "technically flawless", "clarity", "under magnification"],
    entities: ["clarity", "eye-clean"],
    topics: ["quality", "clarity"],
    source: "expert-curated",
    aliases: ["What is the difference between eye-clean and flawless diamonds?"],
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Do different labs grade diamonds differently?",
    family: "diamond-quality",
    intent: "informational",
    stage: "comparing",
    commercial: 6,
    authority: 9,
    matchTerms: ["gia vs igi", "lab differences", "grading consistency", "which lab"],
    entities: ["grading-lab"],
    topics: ["quality", "certification"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How do jewelers grade diamond clarity under magnification?",
    family: "diamond-quality",
    intent: "informational",
    stage: "researching",
    commercial: 4,
    authority: 8,
    matchTerms: ["10x magnification", "loupe", "grading clarity", "inclusions viewing"],
    entities: ["clarity", "grading-process"],
    topics: ["quality", "clarity"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Can a diamond's color be improved with treatments?",
    family: "diamond-quality",
    intent: "informational",
    stage: "researching",
    commercial: 5,
    authority: 8,
    matchTerms: ["treated diamonds", "color treatment", "irradiated", "undisclosed treatment"],
    entities: ["treatment"],
    topics: ["quality", "color", "trust"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },

  // ---------------------------------------------------------------------
  // cut-and-sparkle (+9)
  // ---------------------------------------------------------------------
  {
    question: "What is light performance and why does it matter?",
    family: "cut-and-sparkle",
    intent: "informational",
    stage: "researching",
    commercial: 7,
    authority: 9,
    matchTerms: ["light performance", "why it matters", "brilliance", "optical performance"],
    entities: ["light-performance"],
    topics: ["cut", "light-performance"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How do diamond proportions affect brilliance?",
    family: "cut-and-sparkle",
    intent: "informational",
    stage: "researching",
    commercial: 6,
    authority: 8,
    matchTerms: ["proportions", "brilliance", "table depth", "pavilion angle"],
    entities: ["proportions"],
    topics: ["cut"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What is light leakage in a diamond?",
    family: "cut-and-sparkle",
    intent: "informational",
    stage: "researching",
    commercial: 6,
    authority: 9,
    matchTerms: ["light leakage", "leakage", "dark patches", "poor cut"],
    entities: ["light-leakage"],
    topics: ["cut", "light-performance"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What is the difference between brilliance and fire in a diamond?",
    family: "cut-and-sparkle",
    intent: "informational",
    stage: "researching",
    commercial: 5,
    authority: 8,
    matchTerms: ["brilliance vs fire", "fire", "scintillation", "sparkle types"],
    entities: ["brilliance", "fire"],
    topics: ["cut", "light-performance"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How is cut quality judged differently in fancy shapes versus round diamonds?",
    family: "cut-and-sparkle",
    intent: "informational",
    stage: "comparing",
    commercial: 7,
    authority: 9,
    matchTerms: ["fancy shape cut", "round vs fancy", "cut grading", "no cut grade"],
    entities: ["fancy-shape", "cut-grade"],
    topics: ["cut", "shapes"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Why does a diamond look different under various lighting?",
    family: "cut-and-sparkle",
    intent: "informational",
    stage: "researching",
    commercial: 6,
    authority: 7,
    matchTerms: ["lighting environments", "looks different", "indoor outdoor lighting"],
    entities: ["lighting"],
    topics: ["cut", "light-performance"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Why do some diamonds look dark in photos or in person?",
    family: "cut-and-sparkle",
    intent: "informational",
    stage: "researching",
    commercial: 7,
    authority: 8,
    matchTerms: ["dark diamonds", "look dark", "photos", "dead spots"],
    entities: ["light-leakage"],
    topics: ["cut", "light-performance"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What is a bow-tie effect in a diamond?",
    family: "cut-and-sparkle",
    intent: "informational",
    stage: "researching",
    commercial: 6,
    authority: 8,
    matchTerms: ["bow-tie effect", "bowtie", "shadow", "fancy shapes"],
    entities: ["bow-tie"],
    topics: ["cut", "shapes"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How can I inspect diamond cut quality beyond the certificate?",
    family: "cut-and-sparkle",
    intent: "informational",
    stage: "comparing",
    commercial: 8,
    authority: 10,
    matchTerms: ["inspect cut quality", "beyond certificate", "in person evaluation"],
    entities: ["cut-grade", "selection-philosophy"],
    topics: ["cut", "trust"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },

  // ---------------------------------------------------------------------
  // natural-versus-lab (+9)
  // ---------------------------------------------------------------------
  {
    question: "Do natural and lab-grown diamonds look different to the eye?",
    family: "natural-versus-lab",
    intent: "informational",
    stage: "comparing",
    commercial: 7,
    authority: 8,
    matchTerms: ["look different", "natural vs lab", "visual difference", "appearance"],
    entities: ["natural-diamond", "lab-grown"],
    topics: ["natural-vs-lab"],
    source: "gsc-fixture",
    sourceRef: "lab grown vs natural diamonds",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Why are lab-grown diamonds less expensive than natural diamonds?",
    family: "natural-versus-lab",
    intent: "informational",
    stage: "researching",
    commercial: 7,
    authority: 7,
    matchTerms: ["less expensive", "why cheaper", "price difference", "lab-grown cost"],
    entities: ["lab-grown", "pricing"],
    topics: ["natural-vs-lab", "pricing"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Are natural diamonds rare?",
    family: "natural-versus-lab",
    intent: "informational",
    stage: "discovering",
    commercial: 5,
    authority: 7,
    matchTerms: ["natural diamonds rare", "rarity", "how rare"],
    entities: ["natural-diamond"],
    topics: ["natural-vs-lab"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Can I trade in a lab-grown diamond later for a natural one?",
    family: "natural-versus-lab",
    intent: "commercial",
    stage: "selecting",
    commercial: 8,
    authority: 6,
    matchTerms: ["trade in", "upgrade later", "lab-grown to natural", "exchange"],
    entities: ["lab-grown", "upgrade-policy"],
    topics: ["natural-vs-lab", "pricing"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Are lab-grown diamonds more ethical than natural diamonds?",
    family: "natural-versus-lab",
    intent: "informational",
    stage: "comparing",
    commercial: 6,
    authority: 8,
    matchTerms: ["ethical", "more ethical", "conflict-free", "sourcing ethics"],
    entities: ["lab-grown", "ethics"],
    topics: ["natural-vs-lab", "trust"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Are environmental claims about lab-grown diamonds accurate?",
    family: "natural-versus-lab",
    intent: "informational",
    stage: "researching",
    commercial: 5,
    authority: 8,
    matchTerms: ["environmental claims", "eco-friendly", "carbon footprint", "accurate"],
    entities: ["lab-grown", "environmental-claims"],
    topics: ["natural-vs-lab", "trust"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Does a lab-grown diamond carry the same emotional meaning as a natural one?",
    family: "natural-versus-lab",
    intent: "informational",
    stage: "discovering",
    commercial: 6,
    authority: 6,
    matchTerms: ["emotional meaning", "sentimental value", "feel the same"],
    entities: ["lab-grown", "natural-diamond"],
    topics: ["natural-vs-lab"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Are natural and lab-grown diamonds graded the same way?",
    family: "natural-versus-lab",
    intent: "informational",
    stage: "researching",
    commercial: 6,
    authority: 8,
    matchTerms: ["graded the same", "grading standards", "four cs lab-grown"],
    entities: ["lab-grown", "grading-report"],
    topics: ["natural-vs-lab", "certification"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Can a jeweler tell a lab-grown diamond from a natural one without special equipment?",
    family: "natural-versus-lab",
    intent: "informational",
    stage: "researching",
    commercial: 5,
    authority: 9,
    matchTerms: ["tell the difference", "detectability", "without equipment", "identify lab-grown"],
    entities: ["lab-grown", "detection"],
    topics: ["natural-vs-lab", "trust"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },

  // ---------------------------------------------------------------------
  // shapes-and-appearance (+9)
  // ---------------------------------------------------------------------
  {
    question: "How does diamond shape affect how it looks on different finger types?",
    family: "shapes-and-appearance",
    intent: "informational",
    stage: "comparing",
    commercial: 7,
    authority: 7,
    matchTerms: ["finger types", "shape looks on hand", "which shape for my hand"],
    entities: ["diamond-shape", "finger-appearance"],
    topics: ["shapes"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Which diamond shapes look more elongated on the finger?",
    family: "shapes-and-appearance",
    intent: "informational",
    stage: "comparing",
    commercial: 6,
    authority: 7,
    matchTerms: ["elongated shapes", "finger-lengthening", "oval marquise pear"],
    entities: ["diamond-shape", "elongation"],
    topics: ["shapes"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Which diamond shapes are prone to a bow-tie effect?",
    family: "shapes-and-appearance",
    intent: "informational",
    stage: "researching",
    commercial: 6,
    authority: 8,
    matchTerms: ["bow-tie shapes", "oval bow tie", "marquise bow tie", "pear bow tie"],
    entities: ["bow-tie", "diamond-shape"],
    topics: ["shapes", "cut"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Are pointed-corner diamond shapes less durable?",
    family: "shapes-and-appearance",
    intent: "informational",
    stage: "researching",
    commercial: 6,
    authority: 8,
    matchTerms: ["pointed corners", "durability", "marquise pear", "chip risk"],
    entities: ["diamond-shape", "durability"],
    topics: ["shapes", "quality"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Which diamond shapes appear most brilliant?",
    family: "shapes-and-appearance",
    intent: "informational",
    stage: "comparing",
    commercial: 7,
    authority: 7,
    matchTerms: ["most brilliant shape", "brightest shape", "round vs cushion vs princess"],
    entities: ["diamond-shape", "brilliance"],
    topics: ["shapes", "cut"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What length-to-width ratio looks best for an oval diamond?",
    family: "shapes-and-appearance",
    intent: "informational",
    stage: "comparing",
    commercial: 7,
    authority: 8,
    matchTerms: ["length to width ratio", "oval ratio", "oval proportions", "ideal ratio"],
    entities: ["oval-shape", "proportions"],
    topics: ["shapes"],
    source: "gsc-fixture",
    sourceRef: "oval engagement ring",
    aliases: ["What is the ideal oval diamond ratio?"],
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Do certain diamond shapes work better with certain ring settings?",
    family: "shapes-and-appearance",
    intent: "informational",
    stage: "selecting",
    commercial: 7,
    authority: 7,
    matchTerms: ["shape and setting", "settings for shapes", "compatibility"],
    entities: ["diamond-shape", "ring-setting"],
    topics: ["shapes", "custom-design"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Should I choose a trendy diamond shape or a timeless one?",
    family: "shapes-and-appearance",
    intent: "informational",
    stage: "comparing",
    commercial: 6,
    authority: 6,
    matchTerms: ["trendy vs timeless", "trends", "classic shape"],
    entities: ["diamond-shape", "trends"],
    topics: ["shapes"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How do I choose a diamond shape if I don't know her preference?",
    family: "shapes-and-appearance",
    intent: "informational",
    stage: "selecting",
    commercial: 7,
    authority: 7,
    matchTerms: ["don't know her preference", "guessing shape", "choosing without knowing"],
    entities: ["diamond-shape"],
    topics: ["shapes", "proposal"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },

  // ---------------------------------------------------------------------
  // pricing-and-budgeting (+10)
  // ---------------------------------------------------------------------
  {
    question: "How should I split my budget between the setting and the diamond?",
    family: "pricing-and-budgeting",
    intent: "commercial",
    stage: "selecting",
    commercial: 9,
    authority: 7,
    matchTerms: ["budget split", "setting vs diamond", "allocation", "how to divide budget"],
    entities: ["budget", "ring-setting"],
    topics: ["pricing", "custom-design"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "At what price point does spending more actually improve how a diamond looks?",
    family: "pricing-and-budgeting",
    intent: "commercial",
    stage: "comparing",
    commercial: 8,
    authority: 8,
    matchTerms: ["price point", "spending more", "improves appearance", "value threshold"],
    entities: ["pricing", "diamond-quality"],
    topics: ["pricing", "quality"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Is there a point where paying more stops making a visible difference?",
    family: "pricing-and-budgeting",
    intent: "informational",
    stage: "comparing",
    commercial: 7,
    authority: 8,
    matchTerms: ["diminishing returns", "paying more", "visible difference", "stops mattering"],
    entities: ["pricing"],
    topics: ["pricing", "quality"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Should I prioritize carat size or diamond quality on a fixed budget?",
    family: "pricing-and-budgeting",
    intent: "commercial",
    stage: "comparing",
    commercial: 9,
    authority: 8,
    matchTerms: ["carat vs quality", "fixed budget", "size vs quality", "prioritize"],
    entities: ["carat", "diamond-quality", "budget"],
    topics: ["pricing", "quality"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Can I finance an engagement ring purchase?",
    family: "pricing-and-budgeting",
    intent: "transactional",
    stage: "ready-to-contact",
    commercial: 9,
    authority: 5,
    matchTerms: ["finance", "financing", "payment plan", "installments"],
    entities: ["financing"],
    topics: ["pricing", "buying-process"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What ongoing costs come with owning an engagement ring?",
    family: "pricing-and-budgeting",
    intent: "informational",
    stage: "post-purchase",
    commercial: 5,
    authority: 6,
    matchTerms: ["ongoing costs", "hidden costs", "insurance cost", "maintenance cost"],
    entities: ["ownership-cost"],
    topics: ["pricing", "maintenance"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How is pricing determined for a custom engagement ring?",
    family: "pricing-and-budgeting",
    intent: "commercial",
    stage: "selecting",
    commercial: 9,
    authority: 8,
    matchTerms: ["custom ring pricing", "how priced", "custom cost breakdown"],
    entities: ["custom-design", "pricing"],
    topics: ["pricing", "custom-design"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How much further does a lab-grown diamond budget stretch than a natural diamond budget?",
    family: "pricing-and-budgeting",
    intent: "commercial",
    stage: "comparing",
    commercial: 8,
    authority: 7,
    matchTerms: ["budget stretch", "lab-grown budget", "natural budget", "how much further"],
    entities: ["lab-grown", "natural-diamond", "budget"],
    topics: ["pricing", "natural-vs-lab"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Why do two diamonds that look identical have different prices?",
    family: "pricing-and-budgeting",
    intent: "informational",
    stage: "researching",
    commercial: 7,
    authority: 9,
    matchTerms: ["identical diamonds", "different prices", "why price differs", "look the same"],
    entities: ["pricing", "diamond-quality"],
    topics: ["pricing", "quality"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What am I paying for beyond the diamond itself when I work with a jeweler?",
    family: "pricing-and-budgeting",
    intent: "informational",
    stage: "researching",
    commercial: 7,
    authority: 8,
    matchTerms: ["beyond the diamond", "service pricing", "what am i paying for", "value of a jeweler"],
    entities: ["pricing", "advisor-value"],
    topics: ["pricing", "trust"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },

  // ---------------------------------------------------------------------
  // custom-design (+9)
  // ---------------------------------------------------------------------
  {
    question: "Are there any downsides to designing a custom engagement ring?",
    family: "custom-design",
    intent: "commercial",
    stage: "comparing",
    commercial: 8,
    authority: 8,
    matchTerms: ["downsides", "disadvantages", "custom ring risks", "drawbacks"],
    entities: ["custom-design"],
    topics: ["custom-design"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How many design revisions are typically included in custom ring design?",
    family: "custom-design",
    intent: "informational",
    stage: "selecting",
    commercial: 7,
    authority: 7,
    matchTerms: ["design revisions", "how many revisions", "included revisions"],
    entities: ["custom-design", "revisions"],
    topics: ["custom-design"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Do I need to pay a deposit for a custom engagement ring?",
    family: "custom-design",
    intent: "transactional",
    stage: "ready-to-contact",
    commercial: 9,
    authority: 6,
    matchTerms: ["deposit", "custom ring deposit", "upfront payment"],
    entities: ["custom-design", "deposit"],
    topics: ["custom-design", "pricing"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What are CAD renderings and how are they used in custom design?",
    family: "custom-design",
    intent: "informational",
    stage: "selecting",
    commercial: 6,
    authority: 7,
    matchTerms: ["CAD renderings", "3d rendering", "design preview", "how used"],
    entities: ["custom-design", "cad-rendering"],
    topics: ["custom-design"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How do I choose the right diamond for a custom setting?",
    family: "custom-design",
    intent: "commercial",
    stage: "selecting",
    commercial: 8,
    authority: 8,
    matchTerms: ["choose diamond", "custom setting", "stone selection", "matching diamond to design"],
    entities: ["custom-design", "diamond-selection"],
    topics: ["custom-design", "quality"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Can I redesign a family heirloom into a new engagement ring?",
    family: "custom-design",
    intent: "commercial",
    stage: "selecting",
    commercial: 8,
    authority: 8,
    matchTerms: ["heirloom redesign", "family heirloom", "repurpose", "reset stone"],
    entities: ["custom-design", "heirloom"],
    topics: ["custom-design"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Can a jeweler recreate a design I found online or on social media?",
    family: "custom-design",
    intent: "commercial",
    stage: "selecting",
    commercial: 8,
    authority: 7,
    matchTerms: ["recreate design", "found online", "inspiration photo", "pinterest ring"],
    entities: ["custom-design", "inspiration"],
    topics: ["custom-design"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Will a custom-designed ring be comfortable to wear every day?",
    family: "custom-design",
    intent: "informational",
    stage: "selecting",
    commercial: 6,
    authority: 6,
    matchTerms: ["comfortable", "everyday wear", "wearability", "custom fit"],
    entities: ["custom-design", "wearability"],
    topics: ["custom-design", "maintenance"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What if I don't like the first custom design proposal?",
    family: "custom-design",
    intent: "informational",
    stage: "selecting",
    commercial: 7,
    authority: 7,
    matchTerms: ["don't like first design", "revise design", "not satisfied", "starting over"],
    entities: ["custom-design", "revisions"],
    topics: ["custom-design", "buying-process"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },

  // ---------------------------------------------------------------------
  // buying-process-anxiety (+8)
  // ---------------------------------------------------------------------
  {
    question: "How do I know if I'm overpaying for a diamond?",
    family: "buying-process-anxiety",
    intent: "informational",
    stage: "comparing",
    commercial: 8,
    authority: 9,
    matchTerms: ["overpaying", "fair price", "am i paying too much", "market rate"],
    entities: ["pricing", "trust"],
    topics: ["buying-process", "pricing"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What if I choose the wrong diamond and regret it later?",
    family: "buying-process-anxiety",
    intent: "informational",
    stage: "comparing",
    commercial: 8,
    authority: 7,
    matchTerms: ["wrong choice", "regret", "fear of choosing wrong", "buyer's remorse"],
    entities: ["decision-anxiety"],
    topics: ["buying-process"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How do I avoid high-pressure sales tactics when buying a diamond?",
    family: "buying-process-anxiety",
    intent: "informational",
    stage: "comparing",
    commercial: 7,
    authority: 9,
    matchTerms: ["pressure tactics", "sales pressure", "avoid pressure", "upselling"],
    entities: ["sales-tactics", "trust"],
    topics: ["buying-process", "trust"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What should I do if there are too many diamond options to choose from?",
    family: "buying-process-anxiety",
    intent: "informational",
    stage: "comparing",
    commercial: 7,
    authority: 7,
    matchTerms: ["too many options", "overwhelmed", "narrowing down choices"],
    entities: ["decision-anxiety"],
    topics: ["buying-process"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Should I shop for an engagement ring alone or bring my partner?",
    family: "buying-process-anxiety",
    intent: "informational",
    stage: "selecting",
    commercial: 6,
    authority: 6,
    matchTerms: ["shop alone", "bring partner", "shopping together", "involve partner"],
    entities: ["proposal", "decision-anxiety"],
    topics: ["buying-process", "proposal"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "When should I stop comparing diamonds and just decide?",
    family: "buying-process-anxiety",
    intent: "informational",
    stage: "selecting",
    commercial: 7,
    authority: 7,
    matchTerms: ["when to stop comparing", "just decide", "analysis paralysis"],
    entities: ["decision-anxiety"],
    topics: ["buying-process"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Is it okay to buy the first diamond that meets my criteria?",
    family: "buying-process-anxiety",
    intent: "informational",
    stage: "selecting",
    commercial: 7,
    authority: 6,
    matchTerms: ["first diamond", "meets criteria", "good enough", "settle on first option"],
    entities: ["decision-anxiety"],
    topics: ["buying-process"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How much technical knowledge do I really need before buying a diamond?",
    family: "buying-process-anxiety",
    intent: "informational",
    stage: "discovering",
    commercial: 6,
    authority: 8,
    matchTerms: ["how much knowledge", "technical knowledge", "do i need to be an expert"],
    entities: ["education", "decision-anxiety"],
    topics: ["buying-process", "education"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },

  // ---------------------------------------------------------------------
  // proposal-and-surprise (+8)
  // ---------------------------------------------------------------------
  {
    question: "What if I don't know her ring size?",
    family: "proposal-and-surprise",
    intent: "informational",
    stage: "selecting",
    commercial: 7,
    authority: 6,
    matchTerms: ["don't know ring size", "unknown ring size", "guessing size"],
    entities: ["ring-size", "proposal"],
    topics: ["proposal"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What if I'm not sure what ring style she would want?",
    family: "proposal-and-surprise",
    intent: "informational",
    stage: "selecting",
    commercial: 7,
    authority: 6,
    matchTerms: ["not sure style", "guessing style", "unknown preference", "style uncertainty"],
    entities: ["proposal", "diamond-shape"],
    topics: ["proposal", "shapes"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Should the proposal ring be a surprise or a collaborative choice?",
    family: "proposal-and-surprise",
    intent: "informational",
    stage: "discovering",
    commercial: 6,
    authority: 6,
    matchTerms: ["surprise or collaborative", "choose together", "surprise proposal"],
    entities: ["proposal"],
    topics: ["proposal"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Can I propose with a placeholder ring and choose the real one together?",
    family: "proposal-and-surprise",
    intent: "commercial",
    stage: "selecting",
    commercial: 8,
    authority: 7,
    matchTerms: ["placeholder ring", "temporary ring", "propose without diamond", "choose together after"],
    entities: ["proposal", "placeholder-ring"],
    topics: ["proposal", "custom-design"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How do I plan a proposal around a tight deadline?",
    family: "proposal-and-surprise",
    intent: "commercial",
    stage: "ready-to-contact",
    commercial: 8,
    authority: 7,
    matchTerms: ["tight deadline", "rush proposal", "short timeline", "quick turnaround"],
    entities: ["proposal", "timeline"],
    topics: ["proposal", "buying-process"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Should I involve her family before proposing?",
    family: "proposal-and-surprise",
    intent: "informational",
    stage: "selecting",
    commercial: 5,
    authority: 5,
    matchTerms: ["involve family", "ask permission", "family blessing", "before proposing"],
    entities: ["proposal", "family-involvement"],
    topics: ["proposal"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How do I discreetly get her ring size or style preferences?",
    family: "proposal-and-surprise",
    intent: "informational",
    stage: "selecting",
    commercial: 7,
    authority: 6,
    matchTerms: ["discreetly find out", "secretly get size", "covert questions", "keep it a secret"],
    entities: ["ring-size", "proposal"],
    topics: ["proposal"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How do I plan a proposal while traveling?",
    family: "proposal-and-surprise",
    intent: "informational",
    stage: "selecting",
    commercial: 6,
    authority: 5,
    matchTerms: ["travel proposal", "propose abroad", "bringing ring on trip", "vacation proposal"],
    entities: ["proposal", "travel"],
    topics: ["proposal"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },

  // ---------------------------------------------------------------------
  // luxury-and-private-client (+7)
  // ---------------------------------------------------------------------
  {
    question: "What should I expect from a concierge diamond buying experience?",
    family: "luxury-and-private-client",
    intent: "commercial",
    stage: "researching",
    commercial: 8,
    authority: 8,
    matchTerms: ["concierge experience", "what to expect", "private buying experience"],
    entities: ["concierge"],
    topics: ["private-client"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How discreet is private diamond sourcing?",
    family: "luxury-and-private-client",
    intent: "informational",
    stage: "researching",
    commercial: 7,
    authority: 8,
    matchTerms: ["discreet sourcing", "private sourcing", "confidential sourcing"],
    entities: ["sourcing", "private-client"],
    topics: ["private-client", "trust"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Are private jeweler appointments confidential?",
    family: "luxury-and-private-client",
    intent: "informational",
    stage: "comparing",
    commercial: 7,
    authority: 7,
    matchTerms: ["confidential appointments", "privacy", "discreet appointment"],
    entities: ["private-appointment"],
    topics: ["private-client"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Can a private jeweler work with clients remotely?",
    family: "luxury-and-private-client",
    intent: "commercial",
    stage: "comparing",
    commercial: 8,
    authority: 7,
    matchTerms: ["remote clients", "work remotely", "virtual consultation", "out of state"],
    entities: ["private-jeweler", "remote-client"],
    topics: ["private-client", "local"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Can a private jeweler source rare or unusual diamonds?",
    family: "luxury-and-private-client",
    intent: "commercial",
    stage: "researching",
    commercial: 7,
    authority: 8,
    matchTerms: ["rare diamonds", "unusual requests", "hard to find diamonds", "specialty sourcing"],
    entities: ["sourcing", "rare-diamond"],
    topics: ["private-client"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How quickly can a private jeweler source a diamond under a deadline?",
    family: "luxury-and-private-client",
    intent: "commercial",
    stage: "ready-to-contact",
    commercial: 9,
    authority: 7,
    matchTerms: ["quickly source", "under a deadline", "time-sensitive sourcing", "rush order"],
    entities: ["sourcing", "timeline"],
    topics: ["private-client", "buying-process"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What protections exist when buying a high-value diamond?",
    family: "luxury-and-private-client",
    intent: "informational",
    stage: "comparing",
    commercial: 7,
    authority: 9,
    matchTerms: ["protections", "high-value diamond", "safeguards", "buyer protection"],
    entities: ["private-client", "trust"],
    topics: ["private-client", "trust"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },

  // ---------------------------------------------------------------------
  // local-charlotte-intent (+8)
  // ---------------------------------------------------------------------
  {
    question: "Is there an engagement ring jeweler near SouthPark Charlotte?",
    family: "local-charlotte-intent",
    intent: "local",
    stage: "ready-to-contact",
    geography: "charlotte",
    commercial: 9,
    authority: 6,
    matchTerms: ["southpark", "charlotte", "engagement ring jeweler", "near southpark"],
    entities: ["southpark", "charlotte"],
    topics: ["local"],
    source: "local-intent-expansion",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Is there a private jeweler serving Ballantyne?",
    family: "local-charlotte-intent",
    intent: "local",
    stage: "ready-to-contact",
    geography: "charlotte",
    commercial: 9,
    authority: 6,
    matchTerms: ["ballantyne", "private jeweler", "serving ballantyne"],
    entities: ["ballantyne", "charlotte"],
    topics: ["local"],
    source: "local-intent-expansion",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Can someone outside Charlotte still work with a Charlotte-based jeweler?",
    family: "local-charlotte-intent",
    intent: "local",
    stage: "comparing",
    geography: "charlotte-metro",
    commercial: 7,
    authority: 6,
    matchTerms: ["outside charlotte", "remote client", "work with charlotte jeweler"],
    entities: ["charlotte", "remote-client"],
    topics: ["local", "private-client"],
    source: "local-intent-expansion",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What should I expect from a Charlotte engagement ring consultation appointment?",
    family: "local-charlotte-intent",
    intent: "local",
    stage: "ready-to-contact",
    geography: "charlotte",
    commercial: 9,
    authority: 7,
    matchTerms: ["consultation appointment", "what to expect", "charlotte appointment"],
    entities: ["charlotte", "private-appointment"],
    topics: ["local", "buying-process"],
    source: "gsc-fixture",
    sourceRef: "engagement rings charlotte nc",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Where do private jeweler consultations take place in Charlotte?",
    family: "local-charlotte-intent",
    intent: "local",
    stage: "researching",
    geography: "charlotte",
    commercial: 7,
    authority: 6,
    matchTerms: ["where consultations happen", "location", "charlotte appointment location"],
    entities: ["charlotte", "private-appointment"],
    topics: ["local"],
    source: "local-intent-expansion",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Is it better to buy locally in Charlotte or online?",
    family: "local-charlotte-intent",
    intent: "local",
    stage: "comparing",
    geography: "charlotte",
    commercial: 8,
    authority: 7,
    matchTerms: ["local vs online", "buy locally", "charlotte or online"],
    entities: ["charlotte", "online-purchase"],
    topics: ["local", "jeweler-comparison"],
    source: "gsc-fixture",
    sourceRef: "engagement rings charlotte nc",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Can I get a custom engagement ring designed in Charlotte?",
    family: "local-charlotte-intent",
    intent: "local",
    stage: "selecting",
    geography: "charlotte",
    commercial: 9,
    authority: 7,
    matchTerms: ["custom engagement rings charlotte", "custom design charlotte", "designed in charlotte"],
    entities: ["charlotte", "custom-design"],
    topics: ["local", "custom-design"],
    source: "gsc-fixture",
    sourceRef: "custom engagement rings charlotte",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Where can I get my engagement ring resized or repaired in Charlotte?",
    family: "local-charlotte-intent",
    intent: "local",
    stage: "post-purchase",
    geography: "charlotte",
    commercial: 6,
    authority: 5,
    matchTerms: ["resized in charlotte", "repaired in charlotte", "local repair", "local resize"],
    entities: ["charlotte", "resizing"],
    topics: ["local", "maintenance"],
    source: "local-intent-expansion",
    stamp: SEED_STAMP_V11,
  },

  // ---------------------------------------------------------------------
  // jeweler-comparison (+8)
  // ---------------------------------------------------------------------
  {
    question: "Should I buy a diamond online or from a local jeweler?",
    family: "jeweler-comparison",
    intent: "commercial",
    stage: "comparing",
    commercial: 8,
    authority: 8,
    matchTerms: ["online or local", "buy online", "local jeweler", "which is better"],
    entities: ["online-purchase", "local-jeweler"],
    topics: ["jeweler-comparison"],
    source: "faq-derived",
    aliases: ["Is it better to buy an engagement ring online or in a store?"],
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What is the difference between an inventory seller and a sourcing advisor?",
    family: "jeweler-comparison",
    intent: "informational",
    stage: "comparing",
    commercial: 7,
    authority: 9,
    matchTerms: ["inventory seller", "sourcing advisor", "difference", "business model"],
    entities: ["selection-philosophy", "sourcing"],
    topics: ["jeweler-comparison", "trust"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What credentials should a jeweler actually have?",
    family: "jeweler-comparison",
    intent: "informational",
    stage: "comparing",
    commercial: 7,
    authority: 9,
    matchTerms: ["credentials", "qualifications", "gemologist certification", "what to look for"],
    entities: ["graduate-gemologist", "credentials"],
    topics: ["jeweler-comparison", "trust"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Do jewelers get commissions that could bias their recommendations?",
    family: "jeweler-comparison",
    intent: "informational",
    stage: "comparing",
    commercial: 6,
    authority: 8,
    matchTerms: ["commission", "bias", "sales incentive", "conflict of interest"],
    entities: ["commission", "trust"],
    topics: ["jeweler-comparison", "trust"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What return or upgrade policies should I look for in a jeweler?",
    family: "jeweler-comparison",
    intent: "commercial",
    stage: "comparing",
    commercial: 8,
    authority: 7,
    matchTerms: ["return policy", "upgrade policy", "what to look for", "exchange policy"],
    entities: ["upgrade-policy"],
    topics: ["jeweler-comparison", "pricing"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How transparent should a jeweler be about pricing and sourcing?",
    family: "jeweler-comparison",
    intent: "informational",
    stage: "comparing",
    commercial: 7,
    authority: 9,
    matchTerms: ["transparency", "pricing transparency", "sourcing transparency"],
    entities: ["trust", "sourcing"],
    topics: ["jeweler-comparison", "trust"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How do I evaluate a jeweler's online reviews?",
    family: "jeweler-comparison",
    intent: "informational",
    stage: "comparing",
    commercial: 6,
    authority: 6,
    matchTerms: ["online reviews", "evaluate reviews", "reputation research"],
    entities: ["reviews"],
    topics: ["jeweler-comparison", "trust"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What are warning signs of an untrustworthy jeweler?",
    family: "jeweler-comparison",
    intent: "informational",
    stage: "comparing",
    commercial: 7,
    authority: 9,
    matchTerms: ["warning signs", "red flags", "untrustworthy", "avoid bad jeweler"],
    entities: ["trust", "red-flags"],
    topics: ["jeweler-comparison", "trust"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },

  // ---------------------------------------------------------------------
  // trust-ethics-credibility (+8)
  // ---------------------------------------------------------------------
  {
    question: "What does it mean for a diamond to be conflict-free?",
    family: "trust-ethics-credibility",
    intent: "informational",
    stage: "researching",
    commercial: 5,
    authority: 8,
    matchTerms: ["conflict-free", "ethical sourcing", "kimberley process", "what it means"],
    entities: ["ethics", "conflict-free"],
    topics: ["trust"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What is the difference between a certification and a gemologist's expertise?",
    family: "trust-ethics-credibility",
    intent: "informational",
    stage: "researching",
    commercial: 6,
    authority: 9,
    matchTerms: ["certification vs expertise", "gemologist expertise", "difference"],
    entities: ["graduate-gemologist", "grading-report"],
    topics: ["trust", "certification"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How should a jeweler disclose diamond treatments?",
    family: "trust-ethics-credibility",
    intent: "informational",
    stage: "researching",
    commercial: 5,
    authority: 8,
    matchTerms: ["disclose treatments", "treatment disclosure", "undisclosed treatment"],
    entities: ["treatment", "disclosure"],
    topics: ["trust", "quality"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How should lab-grown diamonds be represented and disclosed?",
    family: "trust-ethics-credibility",
    intent: "informational",
    stage: "researching",
    commercial: 5,
    authority: 8,
    matchTerms: ["lab-grown disclosure", "representation", "labeled correctly"],
    entities: ["lab-grown", "disclosure"],
    topics: ["trust", "natural-vs-lab"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Should I get an independent appraisal after buying a diamond?",
    family: "trust-ethics-credibility",
    intent: "informational",
    stage: "post-purchase",
    commercial: 6,
    authority: 8,
    matchTerms: ["independent appraisal", "after buying", "third-party appraisal"],
    entities: ["appraisal"],
    topics: ["trust", "maintenance"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How can I independently verify a diamond's grading?",
    family: "trust-ethics-credibility",
    intent: "informational",
    stage: "comparing",
    commercial: 6,
    authority: 9,
    matchTerms: ["verify grading", "independent verification", "second opinion", "confirm grade"],
    entities: ["grading-report", "verification"],
    topics: ["trust", "certification"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How does Hourglass decide which diamonds to recommend?",
    family: "trust-ethics-credibility",
    intent: "informational",
    stage: "researching",
    commercial: 7,
    authority: 9,
    matchTerms: ["how recommendations selected", "decide which diamonds", "selection process"],
    entities: ["selection-philosophy"],
    topics: ["trust", "approach"],
    source: "expert-curated",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What credentials does a Graduate Gemologist certification actually require?",
    family: "trust-ethics-credibility",
    intent: "informational",
    stage: "discovering",
    commercial: 5,
    authority: 9,
    matchTerms: ["graduate gemologist requirements", "GG certification", "what it takes"],
    entities: ["graduate-gemologist"],
    topics: ["trust", "certification"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },

  // ---------------------------------------------------------------------
  // maintenance-repairs-ownership (+10)
  // ---------------------------------------------------------------------
  {
    question: "How often should I get my engagement ring professionally cleaned?",
    family: "maintenance-repairs-ownership",
    intent: "informational",
    stage: "post-purchase",
    commercial: 4,
    authority: 6,
    matchTerms: ["professionally cleaned", "how often", "cleaning frequency"],
    entities: ["ring-care", "cleaning"],
    topics: ["maintenance"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How often should prongs be checked for a loose diamond?",
    family: "maintenance-repairs-ownership",
    intent: "informational",
    stage: "post-purchase",
    commercial: 4,
    authority: 7,
    matchTerms: ["prong check", "loose diamond", "inspection frequency", "prongs"],
    entities: ["ring-care", "prongs"],
    topics: ["maintenance"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Can an engagement ring be resized after the wedding?",
    family: "maintenance-repairs-ownership",
    intent: "informational",
    stage: "post-purchase",
    commercial: 5,
    authority: 6,
    matchTerms: ["resized after wedding", "resizing", "ring size change"],
    entities: ["resizing"],
    topics: ["maintenance"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Do I need insurance for an engagement ring?",
    family: "maintenance-repairs-ownership",
    intent: "informational",
    stage: "post-purchase",
    commercial: 6,
    authority: 7,
    matchTerms: ["ring insurance", "do i need insurance", "insure engagement ring"],
    entities: ["insurance"],
    topics: ["maintenance", "pricing"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How often should a diamond appraisal be updated?",
    family: "maintenance-repairs-ownership",
    intent: "informational",
    stage: "post-purchase",
    commercial: 5,
    authority: 7,
    matchTerms: ["appraisal update", "how often", "re-appraisal", "waxhaw appraisal"],
    entities: ["appraisal"],
    topics: ["maintenance"],
    source: "gsc-fixture",
    sourceRef: "waxhaw diamond appraisal",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What is the difference between a jeweler's warranty and ring insurance?",
    family: "maintenance-repairs-ownership",
    intent: "informational",
    stage: "post-purchase",
    commercial: 5,
    authority: 7,
    matchTerms: ["warranty vs insurance", "difference", "coverage"],
    entities: ["insurance", "warranty"],
    topics: ["maintenance"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What should I do if I lose a diamond from my ring?",
    family: "maintenance-repairs-ownership",
    intent: "informational",
    stage: "post-purchase",
    commercial: 6,
    authority: 7,
    matchTerms: ["lost a diamond", "lost stone", "what to do", "missing diamond"],
    entities: ["ring-care", "insurance"],
    topics: ["maintenance"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Is it safe to wear my engagement ring to the gym, pool, or beach?",
    family: "maintenance-repairs-ownership",
    intent: "informational",
    stage: "post-purchase",
    commercial: 4,
    authority: 6,
    matchTerms: ["gym", "pool", "beach", "safe to wear", "chlorine"],
    entities: ["ring-care"],
    topics: ["maintenance"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How should I store my engagement ring when I'm not wearing it?",
    family: "maintenance-repairs-ownership",
    intent: "informational",
    stage: "post-purchase",
    commercial: 3,
    authority: 5,
    matchTerms: ["storage", "how to store", "not wearing it", "ring box"],
    entities: ["ring-care", "storage"],
    topics: ["maintenance"],
    source: "faq-derived",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "When should I take off my engagement ring?",
    family: "maintenance-repairs-ownership",
    intent: "informational",
    stage: "post-purchase",
    commercial: 3,
    authority: 5,
    matchTerms: ["when to take off", "when not to wear", "remove ring"],
    entities: ["ring-care"],
    topics: ["maintenance"],
    source: "conversation-derived",
    stamp: SEED_STAMP_V11,
  },

  // ---------------------------------------------------------------------
  // status: "duplicate" — near-phrasings resolved to a canonical above
  // (or to an existing V1 active), not counted as separate actives
  // ---------------------------------------------------------------------
  {
    question: "Which diamond certificate should I trust most?",
    family: "beginner-education",
    intent: "informational",
    stage: "researching",
    commercial: 6,
    authority: 9,
    matchTerms: ["which certificate", "trust most", "gia vs igi trust"],
    entities: ["grading-report"],
    topics: ["education", "certification"],
    source: "faq-derived",
    status: "duplicate",
    duplicateOf: "What does a diamond certificate actually tell you?",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Is it better to buy an engagement ring online versus in a physical store?",
    family: "jeweler-comparison",
    intent: "commercial",
    stage: "comparing",
    commercial: 8,
    authority: 8,
    matchTerms: ["online versus store", "physical store", "buy online"],
    entities: ["online-purchase"],
    topics: ["jeweler-comparison"],
    source: "faq-derived",
    status: "duplicate",
    duplicateOf: "Should I buy a diamond online or from a local jeweler?",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "What is the ideal length-to-width ratio for an oval cut diamond?",
    family: "shapes-and-appearance",
    intent: "informational",
    stage: "comparing",
    commercial: 7,
    authority: 8,
    matchTerms: ["oval cut ratio", "ideal ratio", "oval diamond proportions"],
    entities: ["oval-shape"],
    topics: ["shapes"],
    source: "gsc-fixture",
    sourceRef: "oval engagement ring",
    status: "duplicate",
    duplicateOf: "What length-to-width ratio looks best for an oval diamond?",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Are lab created diamonds fake diamonds?",
    family: "natural-versus-lab",
    intent: "informational",
    stage: "discovering",
    commercial: 7,
    authority: 8,
    matchTerms: ["lab created", "fake diamonds", "real or fake"],
    entities: ["lab-grown"],
    topics: ["natural-vs-lab"],
    source: "faq-derived",
    status: "duplicate",
    duplicateOf: "Are lab-grown diamonds real diamonds?",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "How do I know if a jeweler is honest?",
    family: "buying-process-anxiety",
    intent: "commercial",
    stage: "comparing",
    commercial: 9,
    authority: 9,
    matchTerms: ["honest jeweler", "know if honest", "trust signals"],
    entities: ["trust"],
    topics: ["trust", "jeweler-comparison"],
    source: "conversation-derived",
    status: "duplicate",
    duplicateOf: "How can I tell whether a jeweler is trustworthy?",
    stamp: SEED_STAMP_V11,
  },

  // ---------------------------------------------------------------------
  // status: "deferred" — considered but not yet in scope for content
  // ---------------------------------------------------------------------
  {
    question: "What is the best diamond shape for a mother's ring?",
    family: "shapes-and-appearance",
    intent: "informational",
    stage: "discovering",
    commercial: 3,
    authority: 3,
    matchTerms: ["mother's ring", "not an engagement ring"],
    entities: ["diamond-shape"],
    topics: ["shapes"],
    source: "conversation-derived",
    status: "deferred",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Can I buy loose diamonds as a pure investment?",
    family: "pricing-and-budgeting",
    intent: "informational",
    stage: "discovering",
    commercial: 4,
    authority: 3,
    matchTerms: ["investment", "loose diamonds", "diamond investing"],
    entities: ["pricing"],
    topics: ["pricing"],
    source: "conversation-derived",
    status: "deferred",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Do you offer layaway plans for engagement rings?",
    family: "pricing-and-budgeting",
    intent: "transactional",
    stage: "ready-to-contact",
    commercial: 5,
    authority: 3,
    matchTerms: ["layaway", "payment plan", "hold and pay"],
    entities: ["financing"],
    topics: ["pricing"],
    source: "conversation-derived",
    status: "deferred",
    stamp: SEED_STAMP_V11,
  },

  // ---------------------------------------------------------------------
  // status: "rejected" — navigational brand noise, out of scope
  // ---------------------------------------------------------------------
  {
    question: "Blue Nile engagement rings",
    family: "jeweler-comparison",
    intent: "navigational",
    stage: "discovering",
    commercial: 2,
    authority: 1,
    matchTerms: ["blue nile", "brand navigational"],
    entities: ["competitor-brand"],
    topics: ["jeweler-comparison"],
    source: "gsc-fixture",
    status: "rejected",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "James Allen diamond search tool",
    family: "jeweler-comparison",
    intent: "navigational",
    stage: "discovering",
    commercial: 2,
    authority: 1,
    matchTerms: ["james allen", "brand navigational", "diamond search tool"],
    entities: ["competitor-brand"],
    topics: ["jeweler-comparison"],
    source: "gsc-fixture",
    status: "rejected",
    stamp: SEED_STAMP_V11,
  },
  {
    question: "Kay Jewelers engagement ring sale",
    family: "jeweler-comparison",
    intent: "navigational",
    stage: "discovering",
    commercial: 2,
    authority: 1,
    matchTerms: ["kay jewelers", "brand navigational", "sale"],
    entities: ["competitor-brand"],
    topics: ["jeweler-comparison"],
    source: "gsc-fixture",
    status: "rejected",
    stamp: SEED_STAMP_V11,
  },
];
