/**
 * Agent OS cadence definitions — model + eligibility only.
 * Does not execute external jobs, cron, or email.
 */

import { AGENT_OS_PERSISTENCE_SCHEMA_VERSION, type CadenceDefinition } from "./types";

/** Founder-facing timezone for cadence windows; internal stamps remain UTC. */
export const FOUNDER_CADENCE_TIMEZONE = "America/New_York";

const HOUR = 60 * 60 * 1000;
const DAY = 24 * HOUR;

export function defaultCadenceDefinitions(
  nowIso?: string,
): CadenceDefinition[] {
  void nowIso;
  return [
    {
      schemaVersion: AGENT_OS_PERSISTENCE_SCHEMA_VERSION,
      cadenceId: "cos-daily-synthesis",
      scope: "chief-of-staff",
      frequencyClass: "daily",
      intendedTrigger: "scheduled",
      enabled: true,
      minimumIntervalMs: 20 * HOUR,
      freshnessWindowMs: 36 * HOUR,
      sourceRequirements: [],
      degradedRunPolicy: "allow-partial-reconcile",
      skipBehavior: "record-skip",
      catchUpBehavior: "run-if-stale",
      timezone: FOUNDER_CADENCE_TIMEZONE,
      nextEligibleAt: null,
      lastAttemptedAt: null,
      lastSuccessfulAt: null,
      description:
        "Daily Chief of Staff synthesis when fresh executive outputs exist",
    },
    {
      schemaVersion: AGENT_OS_PERSISTENCE_SCHEMA_VERSION,
      cadenceId: "cos-weekly-founder-brief",
      scope: "chief-of-staff",
      frequencyClass: "weekly",
      intendedTrigger: "scheduled",
      enabled: true,
      minimumIntervalMs: 6 * DAY,
      freshnessWindowMs: 8 * DAY,
      sourceRequirements: [],
      degradedRunPolicy: "allow-partial-reconcile",
      skipBehavior: "record-skip",
      catchUpBehavior: "run-once",
      timezone: FOUNDER_CADENCE_TIMEZONE,
      nextEligibleAt: null,
      lastAttemptedAt: null,
      lastSuccessfulAt: null,
      description: "Weekly full founder brief assembly (delivery deferred to next pass)",
    },
    {
      schemaVersion: AGENT_OS_PERSISTENCE_SCHEMA_VERSION,
      cadenceId: "bi-daily-source-health",
      scope: "business-intelligence",
      frequencyClass: "daily",
      intendedTrigger: "scheduled",
      enabled: true,
      minimumIntervalMs: 18 * HOUR,
      freshnessWindowMs: 30 * HOUR,
      sourceRequirements: ["ga4"],
      degradedRunPolicy: "allow-source-health-only",
      skipBehavior: "surface-dependency-gap",
      catchUpBehavior: "run-if-stale",
      timezone: FOUNDER_CADENCE_TIMEZONE,
      nextEligibleAt: null,
      lastAttemptedAt: null,
      lastSuccessfulAt: null,
      description: "Daily BI source-health check (not full journey analysis)",
    },
    {
      schemaVersion: AGENT_OS_PERSISTENCE_SCHEMA_VERSION,
      cadenceId: "bi-weekly-performance",
      scope: "business-intelligence",
      frequencyClass: "weekly",
      intendedTrigger: "scheduled",
      enabled: true,
      minimumIntervalMs: 6 * DAY,
      freshnessWindowMs: 8 * DAY,
      sourceRequirements: ["ga4"],
      degradedRunPolicy: "allow-partial-reconcile",
      skipBehavior: "record-skip",
      catchUpBehavior: "run-once",
      timezone: FOUNDER_CADENCE_TIMEZONE,
      nextEligibleAt: null,
      lastAttemptedAt: null,
      lastSuccessfulAt: null,
      description:
        "Weekly deeper BI performance and journey analysis (weekly-intelligence preferred/supplemental when available — absence degrades, does not hard-block)",
    },
    {
      schemaVersion: AGENT_OS_PERSISTENCE_SCHEMA_VERSION,
      cadenceId: "search-weekly-full",
      scope: "search-strategy",
      frequencyClass: "weekly",
      intendedTrigger: "scheduled",
      enabled: true,
      minimumIntervalMs: 6 * DAY,
      freshnessWindowMs: 8 * DAY,
      sourceRequirements: ["gsc"],
      degradedRunPolicy: "allow-partial-reconcile",
      skipBehavior: "record-skip",
      catchUpBehavior: "run-once",
      timezone: FOUNDER_CADENCE_TIMEZONE,
      nextEligibleAt: null,
      lastAttemptedAt: null,
      lastSuccessfulAt: null,
      description: "Weekly Search Strategy full run (GSC + repository + local)",
    },
    {
      schemaVersion: AGENT_OS_PERSISTENCE_SCHEMA_VERSION,
      cadenceId: "search-daily-source-health",
      scope: "search-strategy",
      frequencyClass: "daily",
      intendedTrigger: "scheduled",
      enabled: true,
      minimumIntervalMs: 20 * HOUR,
      freshnessWindowMs: 30 * HOUR,
      sourceRequirements: ["gsc"],
      degradedRunPolicy: "allow-source-health-only",
      skipBehavior: "skip-quietly",
      catchUpBehavior: "none",
      timezone: FOUNDER_CADENCE_TIMEZONE,
      nextEligibleAt: null,
      lastAttemptedAt: null,
      lastSuccessfulAt: null,
      description: "Low-cost daily Search source-health check when GSC configured",
    },
    {
      schemaVersion: AGENT_OS_PERSISTENCE_SCHEMA_VERSION,
      cadenceId: "content-weekly-inventory",
      scope: "content",
      frequencyClass: "weekly",
      intendedTrigger: "scheduled",
      enabled: true,
      minimumIntervalMs: 6 * DAY,
      freshnessWindowMs: 8 * DAY,
      sourceRequirements: [],
      degradedRunPolicy: "allow-partial-reconcile",
      skipBehavior: "record-skip",
      catchUpBehavior: "run-once",
      timezone: FOUNDER_CADENCE_TIMEZONE,
      nextEligibleAt: null,
      lastAttemptedAt: null,
      lastSuccessfulAt: null,
      description: "Weekly Content inventory and production-priority run",
    },
    {
      schemaVersion: AGENT_OS_PERSISTENCE_SCHEMA_VERSION,
      cadenceId: "content-on-demand-after-publish",
      scope: "content",
      frequencyClass: "on-demand",
      intendedTrigger: "on-demand",
      enabled: true,
      minimumIntervalMs: 0,
      freshnessWindowMs: 3 * DAY,
      sourceRequirements: [],
      degradedRunPolicy: "allow-full-degraded",
      skipBehavior: "skip-quietly",
      catchUpBehavior: "none",
      timezone: FOUNDER_CADENCE_TIMEZONE,
      nextEligibleAt: null,
      lastAttemptedAt: null,
      lastSuccessfulAt: null,
      description: "On-demand Content run after new content is published",
    },
    {
      schemaVersion: AGENT_OS_PERSISTENCE_SCHEMA_VERSION,
      cadenceId: "opportunity-weekly-scan",
      scope: "opportunity",
      frequencyClass: "weekly",
      intendedTrigger: "scheduled",
      enabled: true,
      minimumIntervalMs: 6 * DAY,
      freshnessWindowMs: 8 * DAY,
      sourceRequirements: [],
      degradedRunPolicy: "allow-partial-reconcile",
      skipBehavior: "record-skip",
      catchUpBehavior: "run-once",
      timezone: FOUNDER_CADENCE_TIMEZONE,
      nextEligibleAt: null,
      lastAttemptedAt: null,
      lastSuccessfulAt: null,
      description: "Weekly Opportunity scan",
    },
    {
      schemaVersion: AGENT_OS_PERSISTENCE_SCHEMA_VERSION,
      cadenceId: "agent-os-on-demand",
      scope: "agent-os",
      frequencyClass: "on-demand",
      intendedTrigger: "on-demand",
      enabled: true,
      minimumIntervalMs: 0,
      freshnessWindowMs: DAY,
      sourceRequirements: [],
      degradedRunPolicy: "allow-full-degraded",
      skipBehavior: "skip-quietly",
      catchUpBehavior: "none",
      timezone: FOUNDER_CADENCE_TIMEZONE,
      nextEligibleAt: null,
      lastAttemptedAt: null,
      lastSuccessfulAt: null,
      description: "Manual / on-demand Agent OS full brief (bypasses schedule)",
    },
  ];
}

export function getCadenceById(
  cadenceId: string,
  cadences?: CadenceDefinition[],
): CadenceDefinition | undefined {
  return (cadences ?? defaultCadenceDefinitions()).find(
    (c) => c.cadenceId === cadenceId,
  );
}
