import { emptyReportFields } from "./fields";
import type { CalibrationLab, CalibrationReportFields } from "./types";

export type SyntheticCalibrationTier =
  | "elite-reference"
  | "strong-commercial"
  | "average-commercial"
  | "tradeoff-heavy"
  | "clear-compromise";

export type SyntheticCalibrationFixture = {
  id: string;
  reportNumber: string;
  lab: CalibrationLab;
  tier: SyntheticCalibrationTier;
  tierLabel: string;
  /** Controlled normalized inputs — no parser. */
  fields: Partial<CalibrationReportFields>;
  designNote: string;
};

const EX_FINISH = {
  girdle: "Medium, Faceted",
  culet: "None",
  polish: "Excellent",
  symmetry: "Excellent",
  fluorescence: "None",
  cutGrade: "Excellent",
};

const VG_FINISH = {
  girdle: "Medium, Faceted",
  culet: "None",
  polish: "Very Good",
  symmetry: "Very Good",
  fluorescence: "None",
  cutGrade: "Very Good",
};

const MIXED_FINISH = {
  girdle: "Slightly Thick, Faceted",
  culet: "Small",
  polish: "Good",
  symmetry: "Good",
  fluorescence: "Faint",
  cutGrade: "Good",
};

const WEAK_FINISH = {
  girdle: "Thick, Faceted",
  culet: "Medium",
  polish: "Good",
  symmetry: "Fair",
  fluorescence: "Medium",
  cutGrade: "Good",
};

/** Intentionally mixed-quality synthetic round brilliants for distribution calibration. */
export function buildSyntheticCalibrationFixtures(): SyntheticCalibrationFixture[] {
  const base = (): Partial<CalibrationReportFields> => ({
    shape: "Round Brilliant",
    carat: "1.50",
    measurements: "7.40 - 7.43 x 4.55 mm",
  });

  return [
    // —— Elite reference (target 9.3–10) ——
    {
      id: "synth-elite-001",
      reportNumber: "SYNTH-ELITE-001",
      lab: "GIA",
      tier: "elite-reference",
      tierLabel: "Elite optical reference",
      designNote: "Ideal proportion stack — rare top-end architecture",
      fields: {
        ...base(),
        ...EX_FINISH,
        tablePercent: "57",
        depthPercent: "61",
        crownAngle: "34.5",
        pavilionAngle: "40.8",
        lowerHalfPercent: "77",
        starLengthPercent: "50",
      },
    },
    {
      id: "synth-elite-002",
      reportNumber: "SYNTH-ELITE-002",
      lab: "GCAL",
      tier: "elite-reference",
      tierLabel: "Elite optical reference",
      designNote: "Tight crown/pavilion pairing",
      fields: {
        ...base(),
        ...EX_FINISH,
        tablePercent: "56",
        depthPercent: "61.2",
        crownAngle: "34",
        pavilionAngle: "40.75",
        lowerHalfPercent: "78",
        starLengthPercent: "49",
      },
    },
    {
      id: "synth-elite-003",
      reportNumber: "SYNTH-ELITE-003",
      lab: "IGI",
      tier: "elite-reference",
      tierLabel: "Elite optical reference",
      designNote: "Balanced star/lower-half",
      fields: {
        ...base(),
        ...EX_FINISH,
        tablePercent: "57",
        depthPercent: "60.8",
        crownAngle: "35",
        pavilionAngle: "40.9",
        lowerHalfPercent: "76",
        starLengthPercent: "51",
      },
    },
    {
      id: "synth-elite-004",
      reportNumber: "SYNTH-ELITE-004",
      lab: "GIA",
      tier: "elite-reference",
      tierLabel: "Elite optical reference",
      designNote: "Low spread, strong pavilion control",
      fields: {
        ...base(),
        ...EX_FINISH,
        tablePercent: "55",
        depthPercent: "61.5",
        crownAngle: "34.5",
        pavilionAngle: "40.7",
        lowerHalfPercent: "77",
        starLengthPercent: "48",
      },
    },
    {
      id: "synth-elite-005",
      reportNumber: "SYNTH-ELITE-005",
      lab: "GCAL",
      tier: "elite-reference",
      tierLabel: "Elite optical reference",
      designNote: "Reference stone for ceiling calibration",
      fields: {
        ...base(),
        ...EX_FINISH,
        tablePercent: "57",
        depthPercent: "61",
        crownAngle: "34.5",
        pavilionAngle: "40.8",
        lowerHalfPercent: "77.5",
        starLengthPercent: "50",
      },
    },

    // —— Strong commercial / Triple-Ex style (target 7.8–9.0) ——
    {
      id: "synth-comm-001",
      reportNumber: "SYNTH-COMM-001",
      lab: "GIA",
      tier: "strong-commercial",
      tierLabel: "Strong modern commercial",
      designNote: "Typical well-cut Triple Excellent profile",
      fields: {
        ...base(),
        ...EX_FINISH,
        tablePercent: "57",
        depthPercent: "61.5",
        crownAngle: "35",
        pavilionAngle: "40.9",
        lowerHalfPercent: "76",
        starLengthPercent: "52",
      },
    },
    {
      id: "synth-comm-002",
      reportNumber: "SYNTH-COMM-002",
      lab: "IGI",
      tier: "strong-commercial",
      tierLabel: "Strong modern commercial",
      designNote: "Slightly deep but attractive",
      fields: {
        ...base(),
        ...VG_FINISH,
        tablePercent: "56",
        depthPercent: "62",
        crownAngle: "35.5",
        pavilionAngle: "41",
        lowerHalfPercent: "75",
        starLengthPercent: "50",
      },
    },
    {
      id: "synth-comm-003",
      reportNumber: "SYNTH-COMM-003",
      lab: "GCAL",
      tier: "strong-commercial",
      tierLabel: "Strong modern commercial",
      designNote: "8X-style commercial strong",
      fields: {
        ...base(),
        cutGrade: "Excellent",
        polish: "Excellent",
        symmetry: "Excellent",
        girdle: "Medium, Faceted",
        culet: "None",
        fluorescence: "None",
        tablePercent: "58",
        depthPercent: "61",
        crownAngle: "34",
        pavilionAngle: "40.8",
        lowerHalfPercent: "77",
        starLengthPercent: "49",
      },
    },
    {
      id: "synth-comm-004",
      reportNumber: "SYNTH-COMM-004",
      lab: "GIA",
      tier: "strong-commercial",
      tierLabel: "Strong modern commercial",
      designNote: "Wide star, still commercial strong",
      fields: {
        ...base(),
        ...VG_FINISH,
        tablePercent: "57",
        depthPercent: "61.8",
        crownAngle: "34.5",
        pavilionAngle: "40.8",
        lowerHalfPercent: "74",
        starLengthPercent: "54",
      },
    },
    {
      id: "synth-comm-005",
      reportNumber: "SYNTH-COMM-005",
      lab: "IGI",
      tier: "strong-commercial",
      tierLabel: "Strong modern commercial",
      designNote: "Internet inventory strong tier",
      fields: {
        ...base(),
        ...EX_FINISH,
        tablePercent: "56",
        depthPercent: "61.2",
        crownAngle: "35",
        pavilionAngle: "40.7",
        lowerHalfPercent: "76",
        starLengthPercent: "51",
      },
    },
    {
      id: "synth-comm-006",
      reportNumber: "SYNTH-COMM-006",
      lab: "GCAL",
      tier: "strong-commercial",
      tierLabel: "Strong modern commercial",
      designNote: "Mall-grade strong",
      fields: {
        ...base(),
        ...VG_FINISH,
        tablePercent: "57",
        depthPercent: "62.2",
        crownAngle: "34.5",
        pavilionAngle: "41",
        lowerHalfPercent: "75",
        starLengthPercent: "50",
      },
    },
    {
      id: "synth-comm-007",
      reportNumber: "SYNTH-COMM-007",
      lab: "GIA",
      tier: "strong-commercial",
      tierLabel: "Strong modern commercial",
      designNote: "Upper strong band",
      fields: {
        ...base(),
        ...EX_FINISH,
        tablePercent: "55",
        depthPercent: "61",
        crownAngle: "34.5",
        pavilionAngle: "40.85",
        lowerHalfPercent: "77",
        starLengthPercent: "50",
      },
    },
    {
      id: "synth-comm-008",
      reportNumber: "SYNTH-COMM-008",
      lab: "IGI",
      tier: "strong-commercial",
      tierLabel: "Strong modern commercial",
      designNote: "Lower strong — still attractive",
      fields: {
        ...base(),
        ...VG_FINISH,
        tablePercent: "58",
        depthPercent: "61.5",
        crownAngle: "35.5",
        pavilionAngle: "41",
        lowerHalfPercent: "74",
        starLengthPercent: "53",
      },
    },

    // —— Average commercial (target 6.5–8.0) ——
    {
      id: "synth-avg-001",
      reportNumber: "SYNTH-AVG-001",
      lab: "GIA",
      tier: "average-commercial",
      tierLabel: "Average commercial inventory",
      designNote: "Common attractive mall stone",
      fields: {
        ...base(),
        ...MIXED_FINISH,
        tablePercent: "58",
        depthPercent: "62.5",
        crownAngle: "35.5",
        pavilionAngle: "41.1",
        lowerHalfPercent: "73",
        starLengthPercent: "54",
      },
    },
    {
      id: "synth-avg-002",
      reportNumber: "SYNTH-AVG-002",
      lab: "IGI",
      tier: "average-commercial",
      tierLabel: "Average commercial inventory",
      designNote: "Fine jewelry average",
      fields: {
        ...base(),
        ...MIXED_FINISH,
        tablePercent: "57",
        depthPercent: "62",
        crownAngle: "36",
        pavilionAngle: "41",
        lowerHalfPercent: "72",
        starLengthPercent: "55",
      },
    },
    {
      id: "synth-avg-003",
      reportNumber: "SYNTH-AVG-003",
      lab: "GCAL",
      tier: "average-commercial",
      tierLabel: "Average commercial inventory",
      designNote: "Slightly spready average",
      fields: {
        ...base(),
        ...VG_FINISH,
        tablePercent: "58",
        depthPercent: "59.5",
        crownAngle: "33.5",
        pavilionAngle: "40.5",
        lowerHalfPercent: "74",
        starLengthPercent: "52",
      },
    },
    {
      id: "synth-avg-004",
      reportNumber: "SYNTH-AVG-004",
      lab: "GIA",
      tier: "average-commercial",
      tierLabel: "Average commercial inventory",
      designNote: "Balanced commercial mid",
      fields: {
        ...base(),
        ...MIXED_FINISH,
        tablePercent: "56",
        depthPercent: "61.8",
        crownAngle: "35",
        pavilionAngle: "40.9",
        lowerHalfPercent: "71",
        starLengthPercent: "56",
      },
    },
    {
      id: "synth-avg-005",
      reportNumber: "SYNTH-AVG-005",
      lab: "IGI",
      tier: "average-commercial",
      tierLabel: "Average commercial inventory",
      designNote: "Still beautiful — balanced band",
      fields: {
        ...base(),
        polish: "Good",
        symmetry: "Very Good",
        girdle: "Medium to Slightly Thick, Faceted",
        culet: "None",
        fluorescence: "None",
        cutGrade: "Very Good",
        tablePercent: "57",
        depthPercent: "62.3",
        crownAngle: "36",
        pavilionAngle: "41.2",
        lowerHalfPercent: "70",
        starLengthPercent: "57",
      },
    },
    {
      id: "synth-avg-006",
      reportNumber: "SYNTH-AVG-006",
      lab: "GCAL",
      tier: "average-commercial",
      tierLabel: "Average commercial inventory",
      designNote: "Online inventory average",
      fields: {
        ...base(),
        ...MIXED_FINISH,
        tablePercent: "59",
        depthPercent: "61",
        crownAngle: "34.5",
        pavilionAngle: "40.8",
        lowerHalfPercent: "69",
        starLengthPercent: "58",
      },
    },
    {
      id: "synth-avg-007",
      reportNumber: "SYNTH-AVG-007",
      lab: "GIA",
      tier: "average-commercial",
      tierLabel: "Average commercial inventory",
      designNote: "Crown-heavy average",
      fields: {
        ...base(),
        ...VG_FINISH,
        tablePercent: "56",
        depthPercent: "62",
        crownAngle: "36.5",
        pavilionAngle: "40.8",
        lowerHalfPercent: "72",
        starLengthPercent: "54",
      },
    },
    {
      id: "synth-avg-008",
      reportNumber: "SYNTH-AVG-008",
      lab: "IGI",
      tier: "average-commercial",
      tierLabel: "Average commercial inventory",
      designNote: "Lower average — still wearable",
      fields: {
        ...base(),
        ...MIXED_FINISH,
        tablePercent: "58",
        depthPercent: "62.8",
        crownAngle: "36",
        pavilionAngle: "41.3",
        lowerHalfPercent: "68",
        starLengthPercent: "59",
      },
    },

    // —— Tradeoff-heavy (target 5.0–7.5) ——
    {
      id: "synth-trade-001",
      reportNumber: "SYNTH-TRADE-001",
      lab: "GIA",
      tier: "tradeoff-heavy",
      tierLabel: "Tradeoff-heavy architecture",
      designNote: "Steep/deep combination",
      fields: {
        ...base(),
        ...MIXED_FINISH,
        tablePercent: "56",
        depthPercent: "63",
        crownAngle: "36.5",
        pavilionAngle: "41.5",
        lowerHalfPercent: "72",
        starLengthPercent: "50",
      },
    },
    {
      id: "synth-trade-002",
      reportNumber: "SYNTH-TRADE-002",
      lab: "IGI",
      tier: "tradeoff-heavy",
      tierLabel: "Tradeoff-heavy architecture",
      designNote: "Shallow/spready",
      fields: {
        ...base(),
        ...WEAK_FINISH,
        tablePercent: "58",
        depthPercent: "59",
        crownAngle: "32.5",
        pavilionAngle: "40.2",
        lowerHalfPercent: "80",
        starLengthPercent: "45",
      },
    },
    {
      id: "synth-trade-003",
      reportNumber: "SYNTH-TRADE-003",
      lab: "GCAL",
      tier: "tradeoff-heavy",
      tierLabel: "Tradeoff-heavy architecture",
      designNote: "Large table tradeoff",
      fields: {
        ...base(),
        ...MIXED_FINISH,
        tablePercent: "58",
        depthPercent: "61",
        crownAngle: "33",
        pavilionAngle: "40.8",
        lowerHalfPercent: "65",
        starLengthPercent: "58",
      },
    },
    {
      id: "synth-trade-004",
      reportNumber: "SYNTH-TRADE-004",
      lab: "GIA",
      tier: "tradeoff-heavy",
      tierLabel: "Tradeoff-heavy architecture",
      designNote: "Shallow crown",
      fields: {
        ...base(),
        ...VG_FINISH,
        tablePercent: "57",
        depthPercent: "60",
        crownAngle: "31.5",
        pavilionAngle: "40.5",
        lowerHalfPercent: "78",
        starLengthPercent: "48",
      },
    },
    {
      id: "synth-trade-005",
      reportNumber: "SYNTH-TRADE-005",
      lab: "IGI",
      tier: "tradeoff-heavy",
      tierLabel: "Tradeoff-heavy architecture",
      designNote: "Deep pavilion",
      fields: {
        ...base(),
        ...MIXED_FINISH,
        tablePercent: "55",
        depthPercent: "63.5",
        crownAngle: "34.5",
        pavilionAngle: "41.8",
        lowerHalfPercent: "70",
        starLengthPercent: "52",
      },
    },
    {
      id: "synth-trade-006",
      reportNumber: "SYNTH-TRADE-006",
      lab: "GCAL",
      tier: "tradeoff-heavy",
      tierLabel: "Tradeoff-heavy architecture",
      designNote: "Weak spread / lower half short",
      fields: {
        ...base(),
        ...WEAK_FINISH,
        tablePercent: "57",
        depthPercent: "61.5",
        crownAngle: "35",
        pavilionAngle: "40.8",
        lowerHalfPercent: "65",
        starLengthPercent: "60",
      },
    },
    {
      id: "synth-trade-007",
      reportNumber: "SYNTH-TRADE-007",
      lab: "GIA",
      tier: "tradeoff-heavy",
      tierLabel: "Tradeoff-heavy architecture",
      designNote: "Strong spread, weaker optics",
      fields: {
        ...base(),
        polish: "Good",
        symmetry: "Good",
        girdle: "Medium, Faceted",
        culet: "Small",
        fluorescence: "Faint",
        cutGrade: "Very Good",
        tablePercent: "56",
        depthPercent: "60.5",
        crownAngle: "34",
        pavilionAngle: "40.6",
        lowerHalfPercent: "82",
        starLengthPercent: "44",
      },
    },
    {
      id: "synth-trade-008",
      reportNumber: "SYNTH-TRADE-008",
      lab: "IGI",
      tier: "tradeoff-heavy",
      tierLabel: "Tradeoff-heavy architecture",
      designNote: "Mixed finish drag",
      fields: {
        ...base(),
        ...WEAK_FINISH,
        tablePercent: "59",
        depthPercent: "62",
        crownAngle: "37",
        pavilionAngle: "41.2",
        lowerHalfPercent: "68",
        starLengthPercent: "56",
      },
    },
    {
      id: "synth-trade-009",
      reportNumber: "SYNTH-TRADE-009",
      lab: "GCAL",
      tier: "tradeoff-heavy",
      tierLabel: "Tradeoff-heavy architecture",
      designNote: "Table + depth tension",
      fields: {
        ...base(),
        ...MIXED_FINISH,
        tablePercent: "58",
        depthPercent: "63",
        crownAngle: "35.5",
        pavilionAngle: "41.3",
        lowerHalfPercent: "66",
        starLengthPercent: "57",
      },
    },

    // —— Clear compromise (target below ~5.5) ——
    {
      id: "synth-comp-001",
      reportNumber: "SYNTH-COMP-001",
      lab: "GIA",
      tier: "clear-compromise",
      tierLabel: "Clear compromise",
      designNote: "Visibly problematic architecture — user example",
      fields: {
        ...base(),
        ...WEAK_FINISH,
        tablePercent: "64",
        depthPercent: "63.5",
        crownAngle: "37",
        pavilionAngle: "41.8",
        lowerHalfPercent: "72",
        starLengthPercent: "42",
      },
    },
    {
      id: "synth-comp-002",
      reportNumber: "SYNTH-COMP-002",
      lab: "IGI",
      tier: "clear-compromise",
      tierLabel: "Clear compromise",
      designNote: "Extreme table + depth",
      fields: {
        ...base(),
        polish: "Fair",
        symmetry: "Good",
        girdle: "Very Thick, Faceted",
        culet: "Medium",
        fluorescence: "Medium",
        cutGrade: "Good",
        tablePercent: "62",
        depthPercent: "64",
        crownAngle: "38",
        pavilionAngle: "42",
        lowerHalfPercent: "60",
        starLengthPercent: "65",
      },
    },
    {
      id: "synth-comp-003",
      reportNumber: "SYNTH-COMP-003",
      lab: "GCAL",
      tier: "clear-compromise",
      tierLabel: "Clear compromise",
      designNote: "Shallow fish-eye risk profile",
      fields: {
        ...base(),
        ...WEAK_FINISH,
        tablePercent: "60",
        depthPercent: "57",
        crownAngle: "30",
        pavilionAngle: "39.5",
        lowerHalfPercent: "85",
        starLengthPercent: "40",
      },
    },
    {
      id: "synth-comp-004",
      reportNumber: "SYNTH-COMP-004",
      lab: "GIA",
      tier: "clear-compromise",
      tierLabel: "Clear compromise",
      designNote: "Steep crown + deep pavilion",
      fields: {
        ...base(),
        ...WEAK_FINISH,
        tablePercent: "53",
        depthPercent: "64",
        crownAngle: "38",
        pavilionAngle: "42",
        lowerHalfPercent: "58",
        starLengthPercent: "48",
      },
    },
    {
      id: "synth-comp-005",
      reportNumber: "SYNTH-COMP-005",
      lab: "IGI",
      tier: "clear-compromise",
      tierLabel: "Clear compromise",
      designNote: "Poor proportion balance",
      fields: {
        ...base(),
        polish: "Poor",
        symmetry: "Fair",
        girdle: "Extremely Thick, Faceted",
        culet: "Large",
        fluorescence: "Strong",
        cutGrade: "Fair",
        tablePercent: "61",
        depthPercent: "62",
        crownAngle: "37.5",
        pavilionAngle: "41.9",
        lowerHalfPercent: "55",
        starLengthPercent: "62",
      },
    },
    {
      id: "synth-comp-006",
      reportNumber: "SYNTH-COMP-006",
      lab: "GCAL",
      tier: "clear-compromise",
      tierLabel: "Clear compromise",
      designNote: "Significant optical compromise reference",
      fields: {
        ...base(),
        ...WEAK_FINISH,
        tablePercent: "63",
        depthPercent: "63",
        crownAngle: "36.5",
        pavilionAngle: "41.7",
        lowerHalfPercent: "58",
        starLengthPercent: "64",
      },
    },
  ];
}

export function fixtureToFields(
  fixture: SyntheticCalibrationFixture,
): CalibrationReportFields {
  return emptyReportFields(fixture.fields);
}
